### ISSUE TITLE
AWS::CloudFormation::StackSet - New Resource

### ISSUE THREAD

**Issue by ikben** [aws-cloudformation/aws-cloudformation-coverage-roadmap#102]
1. Title -> AWS::CloudFormation::StackSet
2. Scope of request -> AWS::CloudFormation::StackSet shoudl create a StackSet that can be used to deploy multiple stack instance over accounts and regions.
3. Expected behavior -> It should allow the definition of a StackSet. Possibly also default deployment options for when a new template is uploaded.
5. Links to existing API doc (optional) -> AWS::CloudFormation::StackSet
6. Category tag (optional) -> Management & Governance

**Comment by PatMyron** [comment]
https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cloudformation/pull/6

**Comment by piersf** [comment]
Hi all,

Are there any updates or any estimation when this will be released? I can see that PR aws-cloudformation/aws-cloudformation-resource-providers-cloudformation#6 has been merged.

Thank you!

**Comment by owrm** [comment]
This will be streamlined by https://github.com/OpenWhere/ow-infrastructure/issues/2224

**Comment by kddejong** [comment]
Released with https://docs.aws.amazon.com/en_us/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-stackset.html
