### ISSUE TITLE
AWS::EC2::VPNConnection-TransitGatewayId (new property)

### ISSUE THREAD

**Issue by TheDanBlanco** [aws-cloudformation/aws-cloudformation-coverage-roadmap#11]
1. Title -> AWS::EC2::VPNConnection-TransitGatewayId (new property) to support Transit Gateway
2. Scope of request -> Allow this property to be supported via Cloudformation to support usage of Transit Gateway
3. Expected behavior -> When a user adds a TransitGatewayId, CloudFormation passes that Id to the VPN Connection request.
4. Test case recommendation (optional) -> 
5. Links to existing API doc (optional) -> https://docs.aws.amazon.com/cli/latest/reference/ec2/create-vpn-connection.html
6. Category tag (optional) -> Compute
7. Any additional context (optional) -> Usage of Transit Gateway isn't sufficient until this requirement is satisfied.

**Comment by manuelcoppotelli** [comment]
Hi,

As far as I can see, the `AWS::EC2::VPNConnection` resource with property `TransitGatewayId` specified creates also the TransitGatwayAttachment.

Is there a way to have the attachment id retrieved?
I was thinking something like:

`!GetAtt VPNConnection.TransitGatwayAttachment`

Would it be possible?
Thanks

Cheers
