### ISSUE TITLE
AWS::Glue::Job-Timeout (new-property)

### ISSUE THREAD

**Issue by straygar** [aws-cloudformation/aws-cloudformation-coverage-roadmap#111]
1. Title -> AWS::Glue::Job-Timeout
2. Scope of request -> AWS::Glue::Job resources are created with the default timeout of 2880 minutes (2 days), with no ability to change this.
3. Expected behavior -> The `Timeout` property should be exposed to allow specifying a timeout in minutes, as you can in the console. This should be an optional parameter, using `Timeout: 2880` by default like the API.
4. Test case recommendation (optional) -> if a new job is created with a timeout flag set to 60 minutes, it should be visible in the console with the timeout set to 60 minutes. No existing jobs should be affected, if the property is not set.
5. Links to existing API doc (optional) -> https://docs.aws.amazon.com/glue/latest/webapi/API_CreateJob.html#Glue-CreateJob-request-Timeout
6. Category tag (optional) -> Analytics

**Comment by pbsinclair42** [comment]
Looks like this is now supported: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html#cfn-glue-job-timeout

**Comment by straygar** [comment]
@pbsinclair42 That's right!

Resolving issue.
