### ISSUE TITLE
Create AWS::MediaConvert::* Resources

### ISSUE THREAD

**Issue by ngamradt-turner** [aws-cloudformation/aws-cloudformation-coverage-roadmap#114]
All of the AWS Console functionality for AWS Elemental MediaConvert needs to be supported in CloudFormation.  This is the console location:

https://us-east-1.console.aws.amazon.com/mediaconvert/home?region=us-east-1#/jobs/create

This service is supported by the CLI and the documentation is here:

https://docs.aws.amazon.com/cli/latest/reference/mediaconvert/index.html

I should be able to create, update, and delete the following:

1. Jobs
2. Queues
3. Presets

All tagging support needs to be there as well.

**Comment by luiseduardocolon** [comment]
We're researching which items make sense to support in CloudFormation.

**Comment by andrewstec** [comment]
I agree. Everything should go in CloudFormation :)
