### ISSUE TITLE
AWS:: FirewallManager::Policy - New Resource

### ISSUE THREAD

**Issue by adamcousins** [aws-cloudformation/aws-cloudformation-coverage-roadmap#135]
1. Title -> AWS::FirewallManager::Policy
2. Scope of request -> New resource required to support AWS Firewall Manager Service managed WebAcls 
3. Expected behavior -> Create/Update/Delete of 'AWS Firewall Manager Service Policy for Multi-Account Rule Groups' like the boto API allows.
4. Test case recommendation (optional) -> 
5. Links to existing API doc (optional) -> Updated API docs at https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/fms.html#FMS.Client.put_policy
6. Category tag (optional) -> Security

**Comment by ev3rl0ng** [comment]
Would love to see this feature as I'm currently working on automation to handle its equivalent with boto3.

**Comment by PatMyron** [comment]
[`AWS::FMS::Policy`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fms-policy.html)

[Release history](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html)

**Comment by atkinsonm** [comment]
I believe this can be closed: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fms-policy.html
