### ISSUE TITLE
AWS::Events::Rule->EventBusName

### ISSUE THREAD

**Issue by mbotmcc** [aws-cloudformation/aws-cloudformation-coverage-roadmap#138]
Quick Sample Summary:
1. Title 
AWS::Events::Rule->EventBusName

2. Scope of request
We should be able to provide the event bus name to create rules for custom events bus

3. Expected behavior
Should be able to create an event rule by adding 
`EventBusName": "aws.partner....`  

5. Links to existing API doc
https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutTargets.html

**Comment by zbintliff** [comment]
Was looking for this today, hope to see it soon

**Comment by jogold** [comment]
Hey @luiseduardocolon,

Is this shipped? I don't see it neither in the CF specifications (https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json) nor in documentation.

Also, the CF specifications don't include the `AWS::Events::EventBus` although it's described in the CF documentation?

**Comment by zbintliff** [comment]
Yes it has shipped: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Events.html

And there is a PR that was just merged for support for SAM, pending release

**Comment by jogold** [comment]
OK, any idea why it doesn't show up in the specs https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json?
