### ISSUE TITLE
AWS::Glue::Job - set Python version (new property)

### ISSUE THREAD

**Issue by tehjayell** [aws-cloudformation/aws-cloudformation-coverage-roadmap#141]
Request to allow AWS::Glue::Job setting Python version like you can with "create-job" Glue CLI

**Comment by pbsinclair42** [comment]
This is already possible: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-job-jobcommand.html#cfn-glue-job-jobcommand-pythonversion

**Comment by chappidm** [comment]
+1

**Comment by luiseduardocolon** [comment]
This appears to be done - moving to shipped.
