### ISSUE TITLE
estimate-template-cost support for nested stacks

### ISSUE THREAD

**Issue by atkinsonm** [aws-cloudformation/aws-cloudformation-coverage-roadmap#146]
Apologies in advance if this belongs elsewhere.

The AWSCLI supports a `estimate-template-cost` command under the `cloudformation` service. However, this command will fail if a nested stack depends on parameters from another stack in its "family".

**Comment by PatMyron** [comment]
Merging into https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/217
