### ISSUE TITLE
AWS::EC2::Instance (set CPU options) (new attribute)

### ISSUE THREAD

**Issue by luiseduardocolon** [aws-cloudformation/aws-cloudformation-coverage-roadmap#15]
1. Title -> Allow CPU options to be specified during instance launch.
2. Scope of request -> As the API, allow for CoreCount and ThreadsPerCore
3. Expected behavior -> See 2.
4. Test case recommendation (optional) -> 
5. Links to existing API doc (optional) -> https://docs.aws.amazon.com/cli/latest/reference/ec2/run-instances.html
6. Category tag (optional) -> Compute
7. Any additional context (optional)

**Comment by talawahtech** [comment]
Are there plans to support this on AWS::EC2::LaunchTemplate as well?
