### ISSUE TITLE
AWS::CloudFormation::Init - Support Python 3 for helper scripts

### ISSUE THREAD

**Issue by tinproject** [aws-cloudformation/aws-cloudformation-coverage-roadmap#151]
## 1. Title 

AWS::CloudFormation::Init - Support Python 3 for helper scripts

## 2. Scope of request 

Currently aws-cfn-bootstrap scripts use Python 2 only syntax, so they are incompatible with Python3.
Latest version of the scripts on the bucket seems that the `aws-cfn-bootstrap` scripts are untouched since almost a year:
```
<Contents>
  <Key>aws-cfn-bootstrap-latest.tar.gz</Key>
  <LastModified>2018-09-04T23:12:44.000Z</LastModified>
  <ETag>"1787d9d75f764f4a79c899ce073d23a8"</ETag>
  <Size>462514</Size>
  <StorageClass>STANDARD</StorageClass>
</Contents>
```
Python 2 End Of Life is coming at the end of this year (2019).
Current Linux distributions only ships Python3.

-> Make helper scripts Python 3 compatible.

## 3. Expected behavior

aws-cfn-bootstrap scripts can be used on machines with only Python 3 installed.

## 5. Helpful Links to speed up research and evaluation

- Helper scripts docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-helper-scripts-reference.html
- Python 2 EOL notice: https://www.python.org/dev/peps/pep-0373/#update
- aws-cfn-bootstrap bucket list: https://s3.amazonaws.com/cloudformation-examples/

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

5. Management (CloudTrail, Config...)
XX. Cloudformation itself??

## 7. Any additional context (optional)

Original AWS Forums message: https://forums.aws.amazon.com/thread.jspa?threadID=305749&tstart=75

**Comment by aptomaKetil** [comment]
Any update on this? Python 2 is now officially dead, but still required for the CloudFormation helper scripts.

**Comment by christopher-snapp** [comment]
I too am wondering what the status of this is.  In the past week Ubuntu 20.04 developers seem to be culling Python2 packages which had been letting me limp along with installing `aws-cfn-bootstrap-latest` but now it appears that the end is here.

**Comment by jplock** [comment]
It would also be nice to support IMDSv2 as well. https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/

Can these scripts be open-sourced and managed on github so people can contribute? I would be happy to submit a PR somewhere for IMDSv2 support.

**Comment by ferricoxide** [comment]
> I too am wondering what the status of this is. In the past week Ubuntu 20.04 developers seem to be culling Python2 packages which had been letting me limp along with installing `aws-cfn-bootstrap-latest` but now it appears that the end is here.

In the middle of rolling out RHEL 8 into AWS. Kind of painful to have to install a wholly-deprecated language-version just so can execute CFn templates to deploy those new instances. :(

**Comment by kteague** [comment]
FYI, this is what I'm using to bootstrap cfn-init on Ubuntu 20 until a Python 3 release of cfn-init is made.

```
apt-get install -y python2 wget
wget https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
tar -xzvf aws-cfn-bootstrap-latest.tar.gz
cd aws-cfn-bootstrap-1.4/
python2 setup.py install
```

**Comment by Juberstine** [comment]
I'd like to see this updated to work for python3.

**Comment by btsteve** [comment]
I need python 3 support too.

**Comment by saion-chatterjee** [comment]
Any expected timeline when can we get this with python 3 ?

**Comment by luiseduardocolon** [comment]
Short answer: about six weeks.  Longer answer: `aws-cfn-bootstrap` package is currently being migrated from Python 2.x to Python 3. The team is actively working on getting this shipped. Current estimate is on or shortly after July 15, 2020.

**Comment by DanyC97** [comment]
> Short answer: about six weeks. Longer answer: `aws-cfn-bootstrap` package is currently being migrated from Python 2.x to Python 3. The team is actively working on getting this shipped. Current estimate is on or shortly after July 15, 2020.

@luiseduardocolon any idea if the plan is to package it in the same way aws cli v2 is being self-contained ? If so would be a massive step fwd as folks won't have to rely on a specific python3 runtime

**Comment by ddsalt** [comment]
python /usr/lib/python2.7/dist-packages/easy_install.py --script-dir /opt/aws/bin https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
Easy install is... a little easier? from the point you have the tar down.

**Comment by jharley** [comment]
A standalone `cfn-signal` would be ideal

**Comment by saion-chatterjee** [comment]
> Short answer: about six weeks. Longer answer: `aws-cfn-bootstrap` package is currently being migrated from Python 2.x to Python 3. The team is actively working on getting this shipped. Current estimate is on or shortly after July 15, 2020.

@luiseduardocolon any update when this will be ready? the previously estimated timeline has already passed.

**Comment by lenguatako** [comment]
Looks like there is a python3 compatible version on [their official docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-helper-scripts-reference.html)

**Comment by luiseduardocolon** [comment]
Helper scripts now support Python 3.4.  See [this](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-helper-scripts-reference.html) doc page for more info (thanks @lenguatako ).

**Comment by rsevillanos** [comment]
This works for me on Ubuntu 18.04 and 20.04
#!/bin/bash -xe
# Logger
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
# Default Package Update
apt-get -qqy update && apt-get -qqy dist-upgrade && apt-get -qqy autoremove && apt-get -qqy autoclean
apt-get -qqy install curl wget
apt-get -qqy install python3-pip python3-setuptools python3-testresources
# installs "aws-cfn-bootstrap-py3-latest.tar.gz" in "/usr/local/bin/" create link in path "/opt/aws/bin"
pip3 install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz
sleep 5
# create directory "/opt/aws/bin"
mkdir -p /opt/aws/bin
# create links aws dir
ln -s /usr/local/bin/cfn-hup /opt/aws/bin/cfn-hup
ln -s /usr/local/bin/cfn-init /opt/aws/bin/cfn-init
ln -s /usr/local/bin/cfn-signal /opt/aws/bin/cfn-signal
ln -s /usr/local/bin/cfn-elect-cmd-leader /opt/aws/bin/cfn-elect-cmd-leader
ln -s /usr/local/bin/cfn-get-metadata /opt/aws/bin/cfn-get-metadata
ln -s /usr/local/bin/cfn-send-cmd-event /opt/aws/bin/cfn-send-cmd-event
ln -s /usr/local/bin/cfn-send-cmd-result /opt/aws/bin/cfn-send-cmd-result
sleep 5
# Call cfn-init script to install files and packages
/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource Ec2Instance --configsets ec2install --region ${AWS::Region}
# Call cfn-signal script to signal the status from cfn-init (via $?) All done so signal success
/opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource Ec2Instance --region ${AWS::Region}

**Comment by ferricoxide** [comment]
> This works for me on Ubuntu 18.04 and 20.04 #!/bin/bash -xe
> 
> […elided…]
> # create links aws dir
> ~~~
> ln -s /usr/local/bin/cfn-hup /opt/aws/bin/cfn-hup
> ln -s /usr/local/bin/cfn-init /opt/aws/bin/cfn-init
> ln -s /usr/local/bin/cfn-signal /opt/aws/bin/cfn-signal
> ln -s /usr/local/bin/cfn-elect-cmd-leader /opt/aws/bin/cfn-elect-cmd-leader
> ln -s /usr/local/bin/cfn-get-metadata /opt/aws/bin/cfn-get-metadata
> ln -s /usr/local/bin/cfn-send-cmd-event /opt/aws/bin/cfn-send-cmd-event
> ln -s /usr/local/bin/cfn-send-cmd-result /opt/aws/bin/cfn-send-cmd-result
> ~~~

Ubuntu doesn't have an `alternatives` command?

**Comment by kabakakao** [comment]
cfn-init is no longer working for ubuntu22.04.
Is there an option, how to fix that issue?

**Comment by pethers** [comment]
Problem running it on Ubuntu22.04 as well. Not working running on python3.10  

Error
cfnbootstrap/packages/requests/cookies.py", line 159, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'

Some solutions discussed at https://www.datasciencelearner.com/attributeerror-module-collections-has-no-attribute-mutablemapping/

"Attributeerror: module collections has no attribute mutablemapping error is because of internal code changes in the 3.10 version. If you are using any syntax related to the collections module which is compatible with the 3.9 version over the python 3.10-based python environment, you will get this error."
