### ISSUE TITLE
AWS::S3::Bucket Transition - DEEP_ARCHIVE doesn't work

### ISSUE THREAD

**Issue by rjpereira** [aws-cloudformation/aws-cloudformation-coverage-roadmap#161]
## 1. Title 

As per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-lifecycleconfig-rule-transition.html it should be able to specify DEEP_ARCHIVE. 
When used though, it returns a message that only the remaining constants are valid values.

**Comment by ckabalan** [comment]
This is currently affecting me when trying to use this against a new bucket in Ohio.
