### ISSUE TITLE
AWS::Config::RemediationConfiguration - Please add support for auto-remediation

### ISSUE THREAD

**Issue by topshelf99** [aws-cloudformation/aws-cloudformation-coverage-roadmap#163]
The **AWS::Config::RemediationConfiguration** resource type does not currently support enabling auto-remediation.

Our CICD process for security compliance leverages CloudFormation StackSets to deploy Lambda-backed AWS Config Rules and SSM Docs with matching remediation configurations. 

Category - 5. Management (CloudTrail, Config...)

**Comment by luiseduardocolon** [comment]
Automatic property should allow for this now.  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-config-remediationconfiguration.html
