### ISSUE TITLE
AWS::IAM::IdentityProvider 

### ISSUE THREAD

**Issue by fimbulvetr** [aws-cloudformation/aws-cloudformation-coverage-roadmap#170]
## Scope of request 
Support an IdentityProvider with cloudformation.
new service support is desired

## Expected behavior

We should be able to use Ref and GetAtt for ClientIDList, ThumbprintList, and URL so we can build policies to allow EKS access.

## Suggest specific test cases

OIDCProvider:
    Type: AWS::IAM::IdentityProvider
    Properties:
      Type: 'OIDC'
      ProviderUrl: 'http://foo.com'
      Audience: 'foobar'

## Helpful Links to speed up research and evaluation
Documentation:
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html

API:
https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateOpenIDConnectProvider.html

Currently this blog posts suggests using terraform: https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/ Under "1. Cluster and OIDC ID provider creation"

**Comment by atkinsonm** [comment]
Related: #43, #53

**Comment by rohits-spec** [comment]
Since we have introduced separate resources for OIDCProvider and SAMLProvider, closing this issue.
