### ISSUE TITLE
Amazon QLDB support (Quantum Ledger Database)

### ISSUE THREAD

**Issue by kennu** [aws-cloudformation/aws-cloudformation-coverage-roadmap#174]
I didn't see QLDB anywhere in the issues or on the roadmap, so I thought I'd mention it here. Jeff Barr's blog post even says that you can create QLDB ledgers and tables with CoudFormation, but I don't think it's possible yet: https://aws.amazon.com/blogs/aws/now-available-amazon-quantum-ledger-database-qldb/

It would be nice to start creating ledgers with CloudFormation because it will probably not be possible to adopt manually created ledgers into CloudFormation stacks later on, and ledgers are intended to exist forever.

**Comment by ikben** [comment]
It's here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-qldb-ledger.html

**Comment by kennu** [comment]
That was quick, awesome :)
