### ISSUE TITLE
AWS::Transfer::User-homedirectory does not indicate requirement for specifying S3 bucket

### ISSUE THREAD

**Issue by kiyose** [aws-cloudformation/aws-cloudformation-coverage-roadmap#175]
## 2. Scope of request 
AWS::Transfer::User-homedirectory does not indicate requirement for specifying S3 bucket

## 3. Expected behavior
In Create i expect that the S3 bucket need not be specified in the home directory field.
According to the instructions on: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-user.html#aws-resource-transfer-user-properties

I should be able specify the HomeDirectory as '/home/username' as such:
```
Properties:
      UserName: 'username'
      HomeDirectory: '/home/username'
```
Doing so results in a permissions issue when trying to view/edit/upload to the home directory from the SFTP client.

The required configuration is as follows
```
Properties:
      UserName:  'username'
      HomeDirectory: '/sftp-s3-bucketname/home/username'
```

Viewing the console for SFTP user creation i see two parts to the homedirectory section.  There is a dropdown with s3 buckets listed and then there is the actual directory specification ('/home/username')

When viewing the newly created user the homedirectory is listed as '/sftp-s3-bucketname/home/username'.   

I expect that either the documentation be updated to indicate that the bucket name is required or that a field be added to CFn to reference the bucket.

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1
Transfer

**Comment by luiseduardocolon** [comment]
It appears the doc page https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-user.html#aws-resource-transfer-user-properties
has been updated to reflect this - 
HomeDirectory
The landing directory (folder) for a user when they log in to the server using their SFTP client.
An example is <your-Amazon-S3-bucket-name>/home/username.
Required: No
(as in, the HomeDirectory attribute is not required, but the s3 bucketname is if you use it.)

I will close this for now, but let me know if this is still an issue.
