### ISSUE TITLE
AWS::RDS (Aurora Cloning Support)

### ISSUE THREAD

**Issue by luiseduardocolon** [aws-cloudformation/aws-cloudformation-coverage-roadmap#18]
Quick Sample Summary:
1. Title -> Add Aurora cloning support within CloudFormation templates.
2. Scope of request -> Be able to set and update cloning properties when creating or updating Aurora databases.
3. Expected behavior -> Follow the options available via the console and CLI.
4. Test case recommendation (optional) -> 
5. Links to existing API doc (optional) -> Maybe similar functionality to 
 https://docs.aws.amazon.com/cli/latest/reference/rds/restore-db-cluster-to-point-in-time.html
6. Category tag (optional) -> Databases
7. Any additional context (optional)

**Comment by rlister** [comment]
Is this supposedly available? I am trying to create a clone using Cloudformation by setting `RestoreType: 'copy-on-write'` in my `AWS::RDS::DBCluster` resource. The cluster creates, but always has subnet set to `default`, despite setting `DbSubnetGroupName` in template.

The same template (with `ResoreType` removed) can be used to create a normal, new cluster with no problem and has the correct subnet group. Similarly, I can create a clone using the CLI (per the docs) and my subnet group with no issues.

This feels like a Cloudformation bug.
