### ISSUE TITLE
New pseudo parameter reference: AWS::OrgId

### ISSUE THREAD

**Issue by pierresteiner** [aws-cloudformation/aws-cloudformation-coverage-roadmap#182]
Referencing The AWS Organization id from CF using this new pseudo parameter would be really convenient.

This could enable sharing resources (s3, lambda, ...) more efficiently to multiple accounts

**Comment by TheDanBlanco** [comment]
this looks like a duplicate of https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/160. please re-open if this isn't the case.
