### ISSUE TITLE
AWS::EC2::LaunchTemplate-Tags

### ISSUE THREAD

**Issue by kcfedun** [aws-cloudformation/aws-cloudformation-coverage-roadmap#184]
## 1. Title 

AWS::EC2::LaunchTemplate supports tagging and untagging. It should be supported in CloudFormation.

## 2. Scope of request 

Allow creation, update, removal of tags on launch templates. CloudFormation Stacks which are tagged should also propagate tags onto launch templates created resources.

## 3. Expected behavior

In Create, it should reference the cloudformation resourceId and stackName, just like other resources managed by CloudFormation, as well as apply Stack Tags or Resource specific Tags.
in Update, change the value of the tag

## 4. Suggest specific test cases

- Adding tags on create of launch templates.
- Adding tags on the update of launch templates.
- Removing tags on the update of launch templates.

## 5. Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-launchtemplate.html

## 6. Category

- EC2 (Launch Templates)

**Comment by gbhosal** [comment]
I need this too.

**Comment by rocksthehouse** [comment]
> I need this too.

Yep we'd like this feature too.

**Comment by ikben** [comment]
@gbhosal @snarf-snarf-snarf You can use the 👍  on the main issue description to show that this is something you'd like. Comments (including this one) send notifications to all participants and watchers of this issue.

**Comment by rohits-spec** [comment]
Launched TagSpecification property in AWS::EC2::LaunchTemplate. Marking it as shipped.
