### ISSUE TITLE
AWS::KMS::Key-Tags

### ISSUE THREAD

**Issue by kalrish** [aws-cloudformation/aws-cloudformation-coverage-roadmap#193]
## 1. Title
`AWS::KMS::Key` resources should **inherit** the **stack tags**, i.e. the tags of the CloudFormation stack that the resource belongs to.

## 2. Scope of request
[`AWS::KMS::Key`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html) already [supports tagging](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html#cfn-kms-key-tags). By default it should inherit the tags of the CloudFormation stack it belongs to, unless tags are explicitly specified.

## 3. Expected behavior
If the `Tags` property is **not** specified for an `AWS::KMS::Key` resource, the KMS key should get the same tags as the CloudFormation stack.

## 4. Suggest specific test cases
Create a stack with an `AWS::KMS::Key`, specifying some tags in the `CreateStack` call. The KMS key should get the same tags.

## 5. Helpful Links to speed up research and evaluation
It would be great if it worked like many other resource types which by default inherit the stack tags.

## 6. Category

Security

**Comment by PatMyron** [comment]
[`AWS::KMS::Key`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html) is now open source and changes can be tracked here: https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-kms/tree/master/key

**Comment by ammokhov** [comment]
this issues has been addressed by this [Pull Request](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-kms/pull/3)

**Comment by pplu** [comment]
@ammokhov: This issue doesn't seem solved / shipped. I have just created a KMS key in a stack, and the default CloudFormation tags have not been assigned to the key.
