### ISSUE TITLE
[AWS::CodePipeline::Pipeline] - Stage Declaration - onFailure 

### ISSUE THREAD

**Issue by jaydm26** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2035]
### Name of the resource

AWS::CodePipeline::Pipeline

### Description

AWS added support for automatic rollbacks in CodePipelines. However, Cloudformation does not seem to be updated.

AWS Docs: https://docs.aws.amazon.com/codepipeline/latest/userguide/stage-rollback-auto.html
Missing in Cloudformation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-stagedeclaration.html

Can this please be added. Currently, this change blocks https://github.com/aws/aws-cdk/issues/30083 in AWS CDK.

**Comment by darlaker** [comment]
Hello, Thank you for your input on this feature. As of August, the documentation has now been updated with the three condition types (beforeEntry, onFailure, onSuccess) as follows. 
        * The three condition types are now updated here for CloudFormation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-stagedeclaration.html
	* The L1 constructs for the three types are now updated here: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codepipeline.CfnPipeline.StageDeclarationProperty.html

Thank you for your question and for helping us to update the docs!
