### ISSUE TITLE
[AWS::Synthetics::Canary] - [Enhancement] - Runtime Support for Python 3.9 and above

### ISSUE THREAD

**Issue by nirmana** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2039]
### Name of the resource

AWS::Synthetics::Canary

### Description

AWS has recently announced the end of life (EOL) for Python 3.8 in AWS Lambda runtimes. Unfortunately, the synthetic canary runtimes have not been updated to support newer Python versions. As a result, the Lambdas generated by synthetic canaries are running on an outdated Python runtime that will soon be obsolete.

AWS Notification on Python 3,8 Runtime the EOL

> Starting on October 14, 2024, Lambda will no longer apply security patches and other updates to the Python 3.8 runtime used by Lambda functions, and functions using Python 3.8 will no longer be eligible for technical support. Also, Python 3.8 will no longer be available in the AWS Console, although you can still create and update functions that use Python 3.8 via AWS CloudFormation, the AWS CLI, AWS SAM, or other tools. Starting February 28, 2025, you will no longer be able to create new Lambda functions using the Python 3.8 runtime. Starting March 31, 2025, you will no longer be able to update existing functions using the Python 3.8 runtime.

Ref: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Library_python_selenium.html#CloudWatch_Synthetics_runtimeversion-syn-python-selenium-3.0

**Comment by fabianf92** [comment]
Hi,
we are currently planning to update all our Lambda functions to Python 3.9+ ahead of the Python 3.8 end-of-life in October. Could you please provide us with a roadmap or any information regarding when the Python 3.9+ runtime will be supported?

**Comment by nirmana** [comment]
Hi @fabianf92, I've just noticed that the newer version (syn-python-selenium-4.0) with python 3.9 is available now. 
Ref: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Library_python_selenium.html#CloudWatch_Synthetics_runtimeversion-syn-python-selenium-4.0
