### ISSUE TITLE
AWS::RDS::DBInstance - [Coverage] - Implement `EngineLifecycleSupport`

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2049]
### Name of the resource

AWS::RDS::DBInstance

### Description

See https://aws.amazon.com/about-aws/whats-new/2024/05/amazon-rds-extended-support-apis-available/
and also https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html

It currently is **not** implemented in CloudFormation (according to the official docs): https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbinstance.html

**Comment by zrfr** [comment]
This is currently in progress (https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/538, https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/539)

**Comment by zrfr** [comment]
The EngineLifecycleSupport property is now available for [AWS::RDS::DBInstance](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbinstance.html#cfn-rds-dbinstance-enginelifecyclesupport) and [AWS::RDS::DBCluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-enginelifecyclesupport).
