### ISSUE TITLE
AWS::ECS::TaskDefinition - [BUG] - expected type: Integer, found: String

### ISSUE THREAD

**Issue by davidgatti** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2097]
### Name of the resource

AWS::ECS::TaskDefinition

### Issue Description

CloudFormation say I have a string when I have an integer.

### Expected Behavior

CFN should correctly figure out the type

### Observed Behavior

I have

```
"HealthCheck": {
    "Command": [
        "CMD-SHELL",
        "exit 0"
    ],
    "Interval": 30,
    "Timeout": 5,
    "Retries": 3,
    "StartPeriod": 0
}
```

And I get

```
#/ContainerDefinitions/0/HealthCheck/Timeout: expected type: Integer, found: String 
#/ContainerDefinitions/0/HealthCheck/Retries: expected type: Integer, found: String 
#/ContainerDefinitions/0/HealthCheck/Interval: expected type: Integer, found: String 
#/ContainerDefinitions/0/HealthCheck/StartPeriod: expected type: Integer, found: String
```

### Test Cases

Int === to Int

### Other Details

This is a breaking change. I'm currently unable to work because I can't deploy a CloudFormation stack that was functioning properly just an hour ago. Our production release has been stalled.

The recent update you released has disrupted previously working functionality, preventing me from working effectively.

**Comment by fierlion** [comment]
Can you share more about the context where you're seeing the issue come up?  How is your cloud formation template being created?  How are you deploying the template which includes this task definition (console upload, CLI command, etc.)?

**Comment by davidgatti** [comment]
Sorry I can't :( I just removed that section to move forward.
