### ISSUE TITLE
AWS::CodeBuild::Project - Add AutoRetryLimit

### ISSUE THREAD

**Issue by mdgm88** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2170]
### Name of the resource

AWS::CodeBuild::Project

### Description

A new feature has been added to the SDK to set the AutoRetryLimit for a CodeBuild Project: https://docs.aws.amazon.com/codebuild/latest/userguide/auto-retry-build.html

It would be nice if support for this was added to AWS::CodeBuild::Project so we can use IaC to configure this new feature

**Comment by colyoonamaz** [comment]
It seems like this feature is currently supported within CFN, but the documentation is slightly out of date. You can create a CodeBuild project with an AutoRetryLimit using the following template:
```
Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: AutoRetryProject
      ServiceRole: <Service Role>
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:1.0
      AutoRetryLimit: 3
      Source:
        Type: GITHUB
        Location: <Source Location>
```

**Comment by mdgm88** [comment]
Thanks. That works, however cfn-lint sees it as invalid. Will need to raise a separate request on that repo

**Comment by mdgm88** [comment]
Raised https://github.com/aws-cloudformation/cfn-lint/issues/3808
