### ISSUE TITLE
[AWS::Organizations::Policy] - [Coverage] - Support resource control policies

### ISSUE THREAD

**Issue by faridnsh** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2183]
### Name of the resource

AWS::Organizations::Policy

### Description

Support management of [resource control policies](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_rcps.html)

**Comment by mdgm88** [comment]
+1

**Comment by ruchirshetye-aws** [comment]
Support for `RESOURCE_CONTROL_POLICY` is now added. 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-organizations-policy.html#cfn-organizations-policy-type

**Comment by kddejong** [comment]
This is available as `RESOURCE_CONTROL_POLICY` in the `Type` field
