### ISSUE TITLE
AWS::EC2::VPCEndpoint-Tags inherited stack tags support missing

### ISSUE THREAD

**Issue by ajoga** [aws-cloudformation/aws-cloudformation-coverage-roadmap#219]
## 1. Title 

AWS::EC2::VPCEndpoint-Tags inherited stack tags support missing

## 2. Scope of request 
 [`AWS::EC2::VPCEndpoint`](https://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html) is taggable by the [EC2 API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTags.html) but not yet with CloudFormation, as reported in #202. 

By default `AWS::EC2::VPCEndpoint` should inherit the tags of the CloudFormation stack it belongs to, unless tags are explicitly specified.

## 3. Expected behavior

[Automatic CloudFormation tags](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html) should be present on `AWS::EC2::VPCEndpoint` resources.

### Test 1

- Create a `AWS::EC2::VPCEndpoint` resource
- Verify that it got the `aws:cloudformation:logical-id`, `aws:cloudformation:stack-id` and `aws:cloudformation:stack-name` tags. 

## 5. Helpful Links to speed up research and evaluation

This issue is linked to #202 which has more references to offer.
This issue is inspired by #203.

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

- Networking & Content
- Management

**Comment by PatMyron** [comment]
[`AWS::EC2::VPCEndpoint`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html) looks to be missing all tagging support, so I'm going to merge this issue in as a subset of https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/196

**Comment by marcheil** [comment]
Updating CF docs would be nice

**Comment by PatMyron** [comment]
@marcheil to clarify, just closed this issue as a duplicate

Still being tracked in https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/196
