### ISSUE TITLE
[AWS::EC2::VPC] - [Coverage] - Manage Block Public Access (BPA)

### ISSUE THREAD

**Issue by yvele** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2194]
### Name of the resource

AWS::EC2::VPC

### Description

Allow to manage VPC Block Public Access (enable/disable and update options):
- https://aws.amazon.com/blogs/networking-and-content-delivery/vpc-block-public-access/
- https://docs.aws.amazon.com/vpc/latest/userguide/security-vpc-bpa.html

### Other Details

Related EC2 API actions:
- [CreateVpcBlockPublicAccessExclusion](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVpcBlockPublicAccessExclusion.html)
- [DeleteVpcBlockPublicAccessExclusion](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DeleteVpcBlockPublicAccessExclusion.html)
- [ModifyVpcBlockPublicAccessExclusion](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyVpcBlockPublicAccessExclusion.html)
- [ModifyVpcBlockPublicAccessOptions](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyVpcBlockPublicAccessOptions.html)

AWS CLI V2 - `ec2`:
- [create-vpc-block-public-access-exclusion](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/create-vpc-block-public-access-exclusion.html)
- [delete-vpc-block-public-access-exclusion](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/delete-vpc-block-public-access-exclusion.html)
- [modify-vpc-block-public-access-exclusion](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/modify-vpc-block-public-access-exclusion.html)
- [modify-vpc-block-public-access-options](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/modify-vpc-block-public-access-options.html)

Console:

<img width="813" alt="image" src="https://github.com/user-attachments/assets/41e25b8b-e224-4033-b769-120344133f33">

**Comment by gravitylow** [comment]
Support for this feature in CloudFormation is now live:
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcblockpublicaccessoptions.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcblockpublicaccessexclusion.html

**Comment by yvele** [comment]
✅ https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/2194#issuecomment-2494739819
