### ISSUE TITLE
AWS::ECR::Repository-ImageTagMutability

### ISSUE THREAD

**Issue by seansummers** [aws-cloudformation/aws-cloudformation-coverage-roadmap#222]
## 1. Title 

AWS::ECR::Repository-ImageTagMutability

## 2. Scope of request 

AWS::ECR::Repository should support the `image-tag-mutability` flag of the ECR CreateRepository call.

## 3. Expected behavior

In Create or Update, `image-tag-mutability` can be set to `IMMUTABLE` as available from the console and cli.

## 5. Helpful Links to speed up research and evaluation

[Amazon ECR UserGuide image-tag-mutability](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-tag-mutability.html)

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Compute (ECR)

**Comment by brainstorm** [comment]
Scientific reproducibility would be more robust with this fix, go #AWS! ;)

Coming from AWS-CDK's issue https://github.com/aws/aws-cdk/issues/4640

**Comment by SimonAdameit** [comment]
It seems this is possible now: https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-tag-mutability.html Can this issue be closed and the downstream issue be tackled?

**Comment by luiseduardocolon** [comment]
Shipped.
