### ISSUE TITLE
AWS::Events::Rule -> Target -> EcsParameters (new properties)(support for scheduled tasks)

### ISSUE THREAD

**Issue by luiseduardocolon** [aws-cloudformation/aws-cloudformation-coverage-roadmap#23]
1. Title -> AWS::Events::Rule -> Target -> EcsParameters (new properties), should work for ECS and Fargate - it should support scheduling of tasks.
2. Scope of request -> Add Group, LaunchType, NetworkConfiguration and PlatformVersion as valid properties in AWS::Events::Rule --> Target --> EcsParameters
3. Expected behavior -> 
4. Test case recommendation (optional) -> 
5. Links to existing API doc (optional) -> 
6. Category tag (optional) -> Compute
7. Any additional context (optional)

See 
CFN ECSParameters: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-ecsparameters.html
CWE ECSParameters: https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_EcsParameters.html

**Comment by jogold** [comment]
This has been `Shipped` but is still labeled `Coming Soon`.
