### ISSUE TITLE
AWS::Logs::LogGroup support for tagging

### ISSUE THREAD

**Issue by ctaintor** [aws-cloudformation/aws-cloudformation-coverage-roadmap#237]
#### Scope of Request

AWS::Logs::LogGroup does not support tagging today

#### Expected behavior

In Create, I should be able to set tags for the log group

#### Links to existing API doc

https://docs.aws.amazon.com/cli/latest/reference/logs/tag-log-group.html

#### Category tag

CloudWatch

**Comment by PatMyron** [comment]
closing as duplicate of https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/77
