### ISSUE TITLE
AWS::AutoScaling::AutoScalingGroup Instance Protection not supported

### ISSUE THREAD

**Issue by dieutoutpuissant** [aws-cloudformation/aws-cloudformation-coverage-roadmap#239]
## Scope of request
AWS::AutoScaling::AutoScalingGroup-InstanceProtection is not supported by CloudFormation yet it can be set via the console and the API.
![image](https://user-images.githubusercontent.com/35447864/67381053-9163b200-f58b-11e9-8f05-eab0805daa01.png)
It could be useful to be able to set it via CloudFormation.

## Expected behavior

In Create, I should be able to set the InstanceProtection attribute

## Helpful Links to speed up research and evaluation

AWS AutoScalingGroup documentation - Controlling Which Auto Scaling Instances Terminate During Scale In : https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-instance-termination.html#instance-protection

AWS EC2 API documentation - SetInstanceProtection : https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_SetInstanceProtection.html

## Category

Compute (EC2/AutoScalingGroup)

**Comment by ARSport** [comment]
Can't agree more, this seems like a big miss on it.

**Comment by sean-kang** [comment]
It is a shame. I was working on creating CloudFormation templates for ECS clusters and kept finding missing features like this.

**Comment by MatteoInfi** [comment]
This feature was already requested in 2015 and is still not available after more than 5 years? 
I hope with the new Capacity providers you will provide it.

**Comment by MatteoInfi** [comment]
> It is a shame. I was working on creating CloudFormation templates for ECS clusters and kept finding missing features like this.

Agree the whole ecosystem around ECS seems pretty immature and full of design flaws, like Capacity providers and circular dependencies.

**Comment by geof2001** [comment]
This seriously isn't fixed yet?  With all the work that they've done with fixing up the ecs capacity provider support in cloudformation you still can't use them because of this.

**Comment by cpollard0** [comment]
I think this has been resolved, but this thread not updated. There is a property for NewInstancesProtectedFromScaleIn available. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#cfn-as-group-newinstancesprotectedfromscalein

**Comment by ARSport** [comment]
> I think this has been resolved, but this thread not updated. There is a property for NewInstancesProtectedFromScaleIn available.
> 
> https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#cfn-as-group-newinstancesprotectedfromscalein

Awesome! Will be giving this thing a shot later

**Comment by rohits-spec** [comment]
This has been addressed https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#cfn-as-group-newinstancesprotectedfromscalein. Closing this issue.
