### ISSUE TITLE
AWS::ElasticSearch::Domain - Support enforce HTTPS 

### ISSUE THREAD

**Issue by steven-cuthill-otm** [aws-cloudformation/aws-cloudformation-coverage-roadmap#240]
Update CFN API to support the AWS::ElasticSearch::Domain resource property of DomainEndpointOptions. 

aes api docs can be found bellow ; 

https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-configuration-api.html#es-configuration-api-datatypes-domainendpointoptions

    "DomainEndpointOptions": {
        "EnforceHTTPS": true|false,
        “TLSSecurityPolicy”: "<Policy-Min-TLS-1-2-2019-07|Policy-Min-TLS-1-0-2019-07>"
    }

**Comment by ueokande** [comment]
see also #201

**Comment by adabir2** [comment]
I'm surprised such an important security property is still not supported in CF!

**Comment by PatMyron** [comment]
tracking more generally in https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/201
