### ISSUE TITLE
AWS::SSM::Association-MaxConcurrency, MaxErrors

### ISSUE THREAD

**Issue by askulkarni2** [aws-cloudformation/aws-cloudformation-coverage-roadmap#242]
## Summary:
1. Title -> AWS::SSM::Association-MaxConcurrency, MaxErrors
2. Scope of request -> AWS::SSM::Association API supports the MaxConcurrency and MaxErrors parameters as per the [documentation](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CreateAssociation.html). It would be great to include this feature as it allows organizations to adjust the concurrency and error thresholds for associations via cloudformation.
3. Expected behavior -> In Create, it should set MaxConcurrency and MaxErrors if provided. For Update, it should update the parameters if provided. For Delete, no action as the resource would be deleted.
4. Links to existing API doc (optional) -> Updated API docs at https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CreateAssociation.html

**Comment by kddejong** [comment]
Looks like this is available.  https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ssm/blob/master/aws-ssm-association/aws-ssm-association.json#L150-L171

@askulkarni2 can you validate you are able to use this as requested?

**Comment by kddejong** [comment]
I'm going to close this issue but totally willing to re-open it if needed.
