### ISSUE TITLE
AWS::ApiGateway::Stage-WebApplicationFirewall

### ISSUE THREAD

**Issue by seanyu4296** [aws-cloudformation/aws-cloudformation-coverage-roadmap#244]
New Attribute

AWS::ApiGateway::Stage-WebApplicationFirewall to set web application firewall using web ACL in api gateway. 

#[Related issue in aws-cdk](https://github.com/aws/aws-cdk/issues/3582)
![62687415-52e14100-b9f9-11e9-8fd6-ecc1adde82b1](https://user-images.githubusercontent.com/11349232/67612888-c5341700-f7d9-11e9-82e1-7645502a20c8.png)

**Comment by seanyu4296** [comment]
https://github.com/aws/aws-cdk/issues/3582

**Comment by chrisoverzero** [comment]
Isn’t this the purpose of the `AWS::WAFRegional::WebACLAssociation` [resource][]? The `ResourceArn` property can accept the ARN of an API Gateway Stage. 

[resource]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafregional-webaclassociation.html

**Comment by seanyu4296** [comment]
Thanks @chrisoverzero tried it today it seems to work, but i noticed cloudformation does not count it as a stack drift when I disassociate my aws resource (api-gateway) to a specific web acl. Do you have any suggestion or solution to this?

**Comment by chrisoverzero** [comment]
Unfortunately, that’s not on [the list of drift-detectable resources][] yet. 

[the list of drift-detectable resources]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-drift-resource-list.html

**Comment by seanyu4296** [comment]
Okay got it! Is there a timeline of it getting in the list? @chrisoverzero

**Comment by chrisoverzero** [comment]
I'm sorry, I have no idea. I'm not affiliated with Amazon -- I'm just a rando who has experience using Web ACLs.

**Comment by seanyu4296** [comment]
Closing this since I think this feature can be done through ```AWS::WAFRegional::WebACLAssociation```
