### ISSUE TITLE
Feature request: Addition of CloudFormation StackName in Template

### ISSUE THREAD

**Issue by AyhanSetirekli** [aws-cloudformation/aws-cloudformation-coverage-roadmap#247]
## Instructions for CloudFormation Coverage New Issues Template

Quick Sample Summary:
1. Title -> AWS::Service::Resource-Attribute-Existing Attribute
2. Scope of request -> AWS::Service::ResourceType::TheResource-ExistingAttribute supports A and B today, but not new C feature.
3. Expected behavior -> In Create, it should include this and this, like the console.  Also include tag creation, like the API allows.
4. Test case recommendation (optional) -> it should help me do X given existing Y (if applicable); it should/shouldn't change Z.
5. Links to existing API doc (optional) -> Updated API docs at https://example.com/api-new.html
6. Category tag (optional) -> Compute
7. Any additional context (optional)

Detailed Instructions to create a new issue here: (delete this text before you save your issue, to keep them as short as possible :) ). 

## 1. Title 
In the format AWS::Service::Resource-Attribute-Existing Attribute) 
Samples:
#### AWS::Service::ExistingResource-ExistingAttribute-NewOption

We are hoping that the title makes it easy for others to scan it quickly in kanban board or issue list. 

## 2. Scope of request 
Whether a new API call requires a new attribute, or a new feature is supported and needs to be added to CloudFormation.  Be as descriptive as possible so that others can +1 your request if it applies to them.
Should fall into the following categories:

   a) new service support is desired
   b) new resource type for an existing service is desired
   c) new attribute for an existing resource is desired 
   d) new option for an existing attribute is desired 
   e) other coverage-related issue with the resource/attribute/option

Samples: 
## 3. Expected behavior

Samples:
#### Any particular or uncommon Delete behavior? What are the expected options?

Feel free to describe other desired and relevant implementation details. 

## 4. Suggest specific test cases

Samples:
## 5. Helpful Links to speed up research and evaluation

Samples:
## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Use the categories as displayed in the AWS Management Console (simplified):

1. Compute (EC2, ECS, EKS, Lambda...)
2. Storage (S3, EFS, Backup...)
3. DB (RDS, DynamoDB...)
4.  Networking & Content (VPC, Route53, API GW,...)
5. Management (CloudTrail, Config...)
6. Machine Learning (SageMaker, ...)
7. Analytics (Athena, EMR, Glue,...)
8. Security (IAM, KMS...)
9. Integration (MQ, SQS, SNS,...)
10. Developer Tools (CodeStar, ...)
11. Other (IoT, Migration, Budgets...)

**Comment by TheDanBlanco** [comment]
i'm not really sure what this is asking for - is this the same as the `${AWS::StackName} pseudo` parameter?

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html

**Comment by rjlohan** [comment]
I'm going to close this issue as my best guess here is that @TheDanBlanco has answered the ask in the title of the issue. If we've misunderstood the ask, please update the issue summary and reopen.
