### ISSUE TITLE
Create AWS::GlobalAccelerator::* Resources

### ISSUE THREAD

**Issue by cagmarco** [aws-cloudformation/aws-cloudformation-coverage-roadmap#255]
Launched on May 14th 2020 https://aws.amazon.com/about-aws/whats-new/2020/05/aws-global-accelerator-supports-aws-cloudformation/

Category: Networking and Content delivery
Project: Shipped

**Comment by andreaswittig** [comment]
Can't wait to provision a Global Accelerator with CloudFormation.

**Comment by jk2l** [comment]
looking forward to it. until then i need to do it the hard way

custom resource here i come

**Comment by stefanolczak** [comment]
We are also looking forward to it. Not having a way to deploy it using cloudformation is blocking us from using the service. Can we have any update when it is planned to be implemented?

**Comment by sprink** [comment]
My organization also needs this. Current workaround is not optimal. Native Cloudformation support is needed.

**Comment by cagmarco** [comment]
This was launched yesterday https://aws.amazon.com/about-aws/whats-new/2020/05/aws-global-accelerator-supports-aws-cloudformation/
