### ISSUE TITLE
AWS::ECS::Cluster - support enabling container insights

### ISSUE THREAD

**Issue by zxkane** [aws-cloudformation/aws-cloudformation-coverage-roadmap#258]
## 1. Title 

AWS::ECS::Cluster - support enabling container insights 

## 2. Scope of request 

There is a new cluster setting of ECS to enable container insights. But it does not support in CloudFormation now. 

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/deploy-container-insights-ECS.html

## 3. Expected behavior

Be able to enable container insights for ECS cluster.

## 4. Suggest specific test cases

n/a

## 5. Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/deploy-container-insights-ECS.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Use the categories as displayed in the AWS Management Console (simplified):

1. Compute (EC2, ECS, EKS, Lambda...)

**Comment by rjpereira** [comment]
+1

**Comment by clareliguori** [comment]
This is now supported:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-cluster-clustersetting.html

**Comment by surajtikoo** [comment]
Did some one tried. It is getting failed only supported 
ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName
      Name: "containerInsights"
      Value: enabled

**Comment by rjpereira** [comment]
Must confess that never was able to get it working, but never had the time
to research what I was doing wrong. Still have it commented out:

  ECSCluster:
    Type: AWS::ECS::Cluster
#    ClusterSettings:
#      - Name: containerInsights
#        Value: enabled

**Comment by asarazan** [comment]
@rjpereira I think the problem is the `-` you have before `Name` -- I don't believe it's a list but just a set of keyval properties, so you would want:

```yaml
ECSCluster:
      Type: AWS::ECS::Cluster
      Properties:
        ClusterSettings:
          Name: containerInsights
          Value: enabled
```

**Comment by dzmitry-kankalovich** [comment]
@rjpereira it could be related to the fact that there must be a feature flag enabled - check this out https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/deploy-container-insights-ECS-cluster.html

**Comment by SoManyHs** [comment]
> This is now supported:
> https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-cluster-clustersetting.html

Note: correct link: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-cluster-clustersettings.html
