### ISSUE TITLE
AWS::ECS::TaskDefinition ContainerDefinition enable firelensConfiguration

### ISSUE THREAD

**Issue by bradrox** [aws-cloudformation/aws-cloudformation-coverage-roadmap#260]
## 1. Title 
AWS::ECS::TaskDefinition-ContainerDefinition-firelensConfiguration

## 2. Scope of request 
FireLens for Amazon ECS enables enables you to use task definition parameters to route logs for log storage and analytics. Creating Amazon ECS task definitions with a FireLens configuration is supported using the AWS SDKs, AWS CLI, and AWS Management Console but is not supported via CloudFormation.

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_firelens.html

## 4. Suggest specific test cases

N/A

## 5. Helpful Links to speed up research and evaluation

Samples:
## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Use the categories as displayed in the AWS Management Console (simplified):

1. Compute (EC2, ECS, EKS, Lambda...)

**Comment by pahud** [comment]
related to https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/265

**Comment by clareliguori** [comment]
This is now supported:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-firelensconfiguration.html
