### ISSUE TITLE
AWS::CodePipeline::Pipeline-Stages-Actions-Add Namesspace Support

### ISSUE THREAD

**Issue by nason** [aws-cloudformation/aws-cloudformation-coverage-roadmap#262]
## 1. Title 
AWS::CodePipeline::Pipeline-Stages-Actions-Add Namespace Support

## 2. Scope of request 
CodePipeline recently added Variables support, which requires a Namespace to be set on an action

CloudFormation does not support this property yet

## 3. Expected behavior

I should be able to set an action's variable namespace

## 4. Suggest specific test cases

N/A

## 5. Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/codepipeline/latest/userguide/actions-variables.html
https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-variables.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Developer Tools

## 7. Any additional context (optional)

N/A

**Comment by cfbarbero** [comment]
I believe support was added for this in December.  

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-stages-actions.html#cfn-codepipeline-pipeline-actiondeclaration-namespace
