### ISSUE TITLE
AWS::EKS::NodeGroup - Managed Node Groups on EKS

### ISSUE THREAD

**Issue by ueokande** [aws-cloudformation/aws-cloudformation-coverage-roadmap#264]
## 2. Scope of request 

   b) new resource type for an existing service is desired

[Managed Node Groups](https://aws.amazon.com/blogs/containers/eks-managed-node-groups/) is now available on EKS!!!

## 3. Expected behavior

In create an EKS cluster with `NodeGroup` resource on CloudFormation, it creates an EKS node group with the cluster.  It also supports to update configurations on the node groups such as `ScalingConfig`.

## 5. Helpful Links to speed up research and evaluation

- [Blog - Extending the EKS API: Managed Node Groups](https://aws.amazon.com/blogs/containers/eks-managed-node-groups/)
- [EKS Documentation](https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html)
- [CreateNodegroup - API Reference](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateNodegroup.html)
- https://github.com/aws/containers-roadmap/issues/139

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

1. Compute (EKS)

**Comment by tabern** [comment]
@ueokande EKS Managed Node Groups is supported by cloud formation, however the documentation is taking a few more days to deploy than we originally expected. EKS Managed Node Groups introduces a new resource type ”AWS::EKS::Nodegroup“ and an update to existing resource type ”AWS::EKS::Cluster“ to add ClusterSecurityGroupId in Cloudformation. The documentation updates for these changes will be published by 11/21.

**Comment by yannickvr** [comment]
Since the documentation still isn't available, for anyone that requires it:

`  NodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref EKSClusterName
      Subnets: !Ref PrSubnets
      NodeRole: !GetAtt NodeInstanceRole.Arn
      NodegroupName: !Sub "${EKSClusterName}-NodeGroup"
      ScalingConfig:
        MinSize: 2
        MaxSize: 5
        DesiredSize: 3`

Boto3 documentation helps for any missing stuff: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/eks.html#EKS.Client.create_nodegroup

**Comment by tabern** [comment]
CloudFormation documentation for EKS Managed Node Groups is now published – https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-nodegroup.html

**Comment by ueokande** [comment]
Thank you for your great job, AWS team!!
