### ISSUE TITLE
AWS::ECS::TaskDefinition-ContainerDefinition-firelensConfiguration

### ISSUE THREAD

**Issue by pahud** [aws-cloudformation/aws-cloudformation-coverage-roadmap#265]
## 2. Scope of request 
   d) new option for an existing attribute is desired 

## 5. Helpful Links to speed up research and evaluation

Samples:

https://github.com/aws-samples/amazon-ecs-firelens-examples/blob/0d2f23c979872152481faf378154aa1147b0e126/examples/fluent-bit/cloudwatchlogs/task-definition.json#L10

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Use the categories as displayed in the AWS Management Console (simplified):

1. Compute (ECS)

**Comment by pahud** [comment]
FirelensConfiguration is supported today!

<img width="1205" alt="圖片" src="https://user-images.githubusercontent.com/278432/69397294-9d749800-0d20-11ea-98ee-a3271d19e769.png">

**Comment by 600lyy** [comment]
Does CloudFormation support all different launch types including Fargate and EC2?
