### ISSUE TITLE
AWS::RDS::OptionGroup-DeletionPolicy

### ISSUE THREAD

**Issue by cpreese** [aws-cloudformation/aws-cloudformation-coverage-roadmap#272]
Scope:
Please add support for DeletionPolicy on the AWS::RDS::OptionGroup

Expected Behavior:
The CloudFormation could include reference to a DeletionPolicy and could specify to Retain the OptionGroup

We use a CloudFormation script to build RDS SQL Server databases for development and testing. On the AWS::RDS::DBInstance we specify DeletionPolicy: Snapshot. 
For these database instance we need to define a RDS options group ( SQLSERVER_BACKUP_RESTORE ) to allow the database to read/write native SQL Server database dumps to/from an S3 bucket.

At the end on the database's life we need to cleanup and use the CloudFormation delete stack function. The delete stack will fail since there are system generated database dumps that reference this option group. 

AWS::RDS::OptionGroup does not currently support a DeletionPolicy. If it did then the CloudFormation script could specify Retain and the CloudFormation script could successfully delete the RDS instance.

Without the DeletionPolicy, you must run the CloudFormation delete stack and after a long time the delete stack will fail, you have to run the delete stack command again and select to retain the OptionGroup for the delete stack to successfully complete.

Suggested specific test cases:

Create a CloudFormation script that creates a SQL Server database instance AWS::RDS::DBInstance with the DeletionPolicy: Snapshot that references an AWS::RDS::OptionGroup with the OptionName SQLSERVER_BACKUP_RESTORE. Specify a DeletionPolicy of Retain for the OptionGroup.
After successful creation use the CloudFormation delete Stack function and confirm that the database instance is deleted, but the OptionGroup and the snapshot database that references the OptionGroup are not deleted.

Helpful Links:

Category:

DB - RDS

**Comment by PatMyron** [comment]
Every resource type, including [`AWS::RDS::OptionGroup`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-optiongroup.html), should support `DeletionPolicy: Retain`. Do you have a template snippet where you're experiencing `DeletionPolicy: Retain` failing?

It is possible for [`DeletionPolicy: Delete` to fail for some resource types](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/224). This can be specific to certain parameter values, so an example template snippet would be helpful for reproducing this issue as well if you're experiencing this

**Comment by cpreese** [comment]
I just tried this again and I cannot reproduce the symptoms I saw earlier this year.  I must have had a typo in my original script.

Thank you for your fast response.
