### ISSUE TITLE
Bug: AWS::WAFv2::IPSet documentation accepts Get/List/Response data

### ISSUE THREAD

**Issue by seittema** [aws-cloudformation/aws-cloudformation-coverage-roadmap#279]
## Scope of request 
The new AWS::WAFv2::IPSet resource has Get/List/Response attributes defined in the CloudFormation spec.  I'm not entirely sure if this is desired given no other CloudFormation resource I've come across provides this data.  The following Attributes are only used when Get/List or paginating through the results of a WAF:
Limit
LockToken
NextMarker
NextLockToken

Furthermore, the Summary attribute is actually the response when you call create_ip_set
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/wafv2.html#WAFV2.Client.create_ip_set

There is also no return data defined either:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafv2-ipset.html

## Expected behavior

I would expect the attributes accepted for the CloudFormation resource would line up with the SDK/CLI accepted values
https://docs.aws.amazon.com/cli/latest/reference/wafv2/create-ip-set.html
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/wafv2.html#WAFV2.Client.create_ip_set
```
(
    Name='string',
    Scope='CLOUDFRONT'|'REGIONAL',
    Description='string',
    IPAddressVersion='IPV4'|'IPV6',
    Addresses=[
        'string',
    ],
    Tags=[
        {
            'Key': 'string',
            'Value': 'string'
        },
    ]
)
```
## Category

Security, Identity, & Compliance

**Comment by luiseduardocolon** [comment]
I was looking at the CloudFormation resource spec for this and could not find the attributes you mention here.  The CloudFormation docs seem to line up with the SDK/CLI values.  Is this still an issue?

**Comment by seittema** [comment]
@luiseduardocolon It appears the page has already been updated and looks correct.  It is still missing the Return Data definitions. Should I separate that out into a new issue?

**Comment by seittema** [comment]
Appears the documentation now has return data. Closing
