### ISSUE TITLE
AWS::ElasticLoadBalancingV2::ListenerRule-Action-ForwardConfig

### ISSUE THREAD

**Issue by callado4** [aws-cloudformation/aws-cloudformation-coverage-roadmap#285]
## 2. Scope of request 

   d) new option for an existing attribute is desired 

Weighted Target Groups were just recently added to ALB but it's not yet in Cloudformation.  

The documentation in Cloudformation does mention the usage of `ForwardConfig` in the `TargetGroupARN` section of `Action` but there is no `ForwardConfig` attribute available yet for `ListenerRule-Action`
>The Amazon Resource Name (ARN) of the target group. Specify only when Type is forward and you want to route to a single target group. To route to one or more target groups, use ForwardConfig instead.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listener-defaultactions.html

The API Reference for the corresponding property `ForwardActionConfig` has been updated:
https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_ForwardActionConfig.html

## 4. Suggest specific test cases

One of the reasons for us to use weighted target groups is to deploy new changes to a subset of users.  We would like to have a listener that can send traffic to a "canary" target group based on a Cloudformation update, but we would also like to setup this "canary" target group and/or set of services/servers behind the target group with the same cloudformation update.  In other words, like a I mentioned above when updating a ForwardConfig with either a new target group or increasing a target group's weight from 0 to >0, the target group should be healthy before it starts to receive traffic.

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

1. Compute

## 7. Any additional context (optional)

Would love to be able to make these changes natively using the AWS CDK too :)

**Comment by PatMyron** [comment]
[`AWS::ElasticLoadBalancingV2::ListenerRule.Action` documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listenerrule-actions.html)

[release history](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html)

[related issue](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/385)
