### ISSUE TITLE
AWS::EC2ImageBuilder::*

### ISSUE THREAD

**Issue by AlexChesters** [aws-cloudformation/aws-cloudformation-coverage-roadmap#292]
## 2. Scope of request 
New service support is desired.

[EC2 Image Builder](https://aws.amazon.com/image-builder/) was released but, as far as I can see, there is no CloudFormation support. Ideally all aspects of EC2 Image Builder could be defined in CloudFormation, including:
AWS::EC2ImageBuilder::Pipeline
AWS::EC2ImageBuilder::Recipe
AWS::EC2ImageBuilder::Component

## 3. Expected behavior
I should be able to use CloudFormation to define and manage my EC2 Image Builder resources.

## 5. Helpful Links to speed up research and evaluation
* [API documentation](https://docs.aws.amazon.com/imagebuilder/latest/APIReference/Welcome.html)
* [Service announcement](https://aws.amazon.com/about-aws/whats-new/2019/12/introducing-ec2-image-builder/)

## 6. Category
Compute

**Comment by nbmha1** [comment]
Would be great to have this!  Creating/updating recipes is a bit cumbersome through the CLI (have to substitute in ARNs)

**Comment by victoravr** [comment]
Yes, looking forward to seeing this!

**Comment by jk2l** [comment]
also for the sake of having support to code versioning with git, CI/CD pipeline deployment. please allow update of resource. don't make it that it is impossible to update resource like the implementation of https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/115

**Comment by greenaussie** [comment]
> Would be great to have this! Creating/updating recipes is a bit cumbersome through the CLI (have to substitute in ARNs)

Totally agree.

**Comment by luiseduardocolon** [comment]
You should expect the following to be released soon:
AWS::ImageBuilder::Image
AWS::ImageBuilder::ImageRecipe
AWS::ImageBuilder::ImagePipeline
AWS::ImageBuilder::InfrastructureConfiguration
AWS::ImageBuilder::DistributionConfiguration
AWS::ImageBuilder::Component

Luis

**Comment by robertd** [comment]
Yay!!! It looks like this got released: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_ImageBuilder.html

https://twitter.com/cfnupdates/status/1258981218617569281?s=20

**Comment by luiseduardocolon** [comment]
Updated title to highlight that this is done, but we called the resource type something slightly different (ImageBuilder vs EC2ImageBuilder)
