### ISSUE TITLE
AWS::ECS::TaskDefinition - (new property) Secrets

### ISSUE THREAD

**Issue by TheDanBlanco** [aws-cloudformation/aws-cloudformation-coverage-roadmap#30]
1. Title -> AWS::EC2::TaskDefinition
2. Scope of request -> AWS::EC2::TaskDefinition currently does not support secrets, but the ECS task definition api call does.
3. Expected behavior -> Secrets should be consumed by TaskDefinition but not leaked.
4. Test case recommendation (optional) -> 
5. Links to existing API doc (optional) -> https://docs.aws.amazon.com/cli/latest/reference/ecs/register-task-definition.html
6. Category tag (optional) -> Compute
7. Any additional context (optional) - > ecs containers roadmap issue: https://github.com/aws/containers-roadmap/issues/97

**Comment by johnktims** [comment]
Should be `AWS::ECS::TaskDefinition` (not EC2).

**Comment by TheDanBlanco** [comment]
Good catch!

**Comment by fstendel** [comment]
Hi,

sorry if don't get the intent of this issues right. 
But cloudformation is already supporting secets, isn't it?

Is this repository the right place to file feature requests/issues regarding current implementation as well?

Tnx
