### ISSUE TITLE
AWS::AppConfig*

### ISSUE THREAD

**Issue by fimbulvetr** [aws-cloudformation/aws-cloudformation-coverage-roadmap#307]
## Scope of request 
There is no support for any of the new AppConfig service resources. This is a request to add them.

## Expected behavior

I should be able to declare AppConfig Apps, Environments, Deployments, Configurations, DeploymentStrategies, ConfigurationProfiles, etc. in cloudformation.

## Helpful Links to speed up research and evaluation

https://aws.amazon.com/blogs/aws/safe-deployment-of-application-configuration-settings-with-aws-appconfig/
https://docs.aws.amazon.com/systems-manager/latest/userguide/appconfig.html
https://docs.aws.amazon.com/appconfig/2019-10-09/APIReference/Welcome.html

## Category (required) - Will help with tagging and be easier to find by other users to +1

Management ? I think

**Comment by benkehoe** [comment]
I would rather this live separately under AWS::AppConfig (as the API does, see links above), as it has a large number of resources that would be well-served by grouping them together rather than using a naming convention inside AWS::SSM

**Comment by fimbulvetr** [comment]
> I would rather this live separately under AWS::AppConfig (as the API does, see links above), as it has a large number of resources that would be well-served by grouping them together rather than using a naming convention inside AWS::SSM

Thanks, you are correct - in the API it's under the AWS::AppConfig namespace. Title has been updated.

**Comment by vinnies1990** [comment]
Hi, 

We have resolved this. The documentation is now live here - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_AppConfig.html

**Comment by vinnies1990** [comment]
@fimbulvetr let me know if this can be resolved.

**Comment by fimbulvetr** [comment]
@vinnies1990 Yep, LGTM, thanks!
