### ISSUE TITLE
AWS::ACM::Certificate 

### ISSUE THREAD

**Issue by rhboyd** [aws-cloudformation/aws-cloudformation-coverage-roadmap#31]
## 1. Title 
AWS::ACM::Certificate-ExistingAttribute-BetterDX

## 2. Scope of request 
other coverage-related issue with the resource/attribute/option

AWS::ACM::Certificate is basically the canonical example of why Custom Resources are needed. It would be great if I could create an ACM cert in CloudFormation and cfn will handle the adding the DNS records.

## 3. Expected behavior

Samples:
## 4. Suggest specific test cases
it should help me create an ACM Certificate given that the same account is the authority for the domain name used in the certificate.

## 5. Helpful Links to speed up research and evaluation.
The Stack should not stay in "Pending" until I do some manual step, it should do it for me.

Updated API docs at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-certificatemanager-certificate.html

## 7. Any additional context (optional)
If you add this, you'll replace DynamoDB as my second favorite service team ;)

**Comment by jthomerson** [comment]
I agree there's a *huge* need for an improvement to ACM cert validation. The fact that you can't actually use DNS validation without manually copying and pasting DNS values from ACM (using CLI, SDK, or web console) is a tragedy (considering us CloudFormation users are hard-core "IaaC or die" zealots 😜).

Here's a blog post explaining how folks have worked around this big hold using custom resources: https://binx.io/blog/2018/10/05/automated-provisioning-of-acm-certificates-using-route53-in-cloudformation/

**Comment by rrrix** [comment]
For reference, here's how the AWS CDK handles this magic (it works wonderfully!)

https://github.com/aws/aws-cdk/blob/1199e33ad72334fc3d89af7dfa018b46b90674d5/packages/%40aws-cdk/aws-certificatemanager/lib/dns-validated-certificate.ts#L57

https://github.com/aws/aws-cdk/blob/1199e33ad72334fc3d89af7dfa018b46b90674d5/packages/%40aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/lib/index.js#L227

**Comment by mbarneyjr** [comment]
This is now supported natively by CloudFormation:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-certificatemanager-certificate-domainvalidationoption.html#cfn-certificatemanager-certificate-domainvalidationoption-hostedzoneid

**Comment by jthomerson** [comment]
@mbarneyjr I can't tell you how excited I am about this. Thank you!

**Comment by Tro95** [comment]
It would be great if #523 can be done as well, as this is a requirement for any CloudFront deployments from regions other than us-east-1.

**Comment by richardhboyd** [comment]
@Tro95 this issue will likely be closed now that the resource is available. i would add your use-case to the issue you linked so it can be tracked there.

**Comment by luiseduardocolon** [comment]
@Tro95 what @richardhboyd said :)
