### ISSUE TITLE
AWS::Elasticsearch::Domain-LogPublishingOptions doesn't match API

### ISSUE THREAD

**Issue by hv-work** [aws-cloudformation/aws-cloudformation-coverage-roadmap#315]
## 2. Scope of request

According to [CF docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-logpublishingoptions):
```
LogPublishingOptions
    Key-value pairs to configure slow log publishing.
```

While [boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/es.html#ElasticsearchService.Client.create_elasticsearch_domain) say:
```
LogPublishingOptions (dict) --
Map of LogType and LogPublishingOption , each containing options to publish a given type of Elasticsearch log.
    (string) --
    Type of Log File, it can be one of the following:
        INDEX_SLOW_LOGS: Index slow logs contain insert requests that took more time than configured index query log threshold to execute.
        SEARCH_SLOW_LOGS: Search slow logs contain search queries that took more time than configured search query log threshold to execute.
        ES_APPLICATION_LOGS: Elasticsearch application logs contain information about errors and warnings raised during the operation of the service and can be useful for troubleshooting.
        (dict) --
        Log Publishing option that is set for given domain. Attributes and their details:
            CloudWatchLogsLogGroupArn: ARN of the Cloudwatch log group to which log needs to be published.
            Enabled: Whether the log publishing for given log type is enabled or not
            CloudWatchLogsLogGroupArn (string) --
            ARN of the Cloudwatch log group to which log needs to be published.
            Enabled (boolean) --
            Specifies whether given log publishing option is enabled or not.
```

## 3. Expected behavior
LogPublishingOptions documentation should match API docs. 

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1
7. Analytics (Athena, EMR, Glue,...)

**Comment by luiseduardocolon** [comment]
To request this doc page to be updated, you can use the Feedback button on the page.  It will take you to:

https://docs-feedback.aws.amazon.com/feedback.jsp?hidden_service_name=CloudSearch&topic_url=http://docs.aws.amazon.com/en_us/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html

I went ahead and requested this on your behalf.  Alternatively, you can also contribute and propose a change directly to the docs at:

https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-resource-elasticsearch-domain.md

I'll close the issue, but we appreciate your participation here.  Happy holidays!
