### ISSUE TITLE
AWS::ElasticSearch::Domain-NewAttribute-HttpsRequired

### ISSUE THREAD

**Issue by rhbecker** [aws-cloudformation/aws-cloudformation-coverage-roadmap#320]
## Scope of request

A new attribute for the [existing elasticsearch-domain resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html) is desired to turn the [recently introduced (October 3, 2019)](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/release-notes.html) feature to [require HTTPS (data protection)](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-data-protection.html) on or off.

## Expected behavior

A boolean value should control whether the enforcement is on or off, just as checking this box in the domain creation UI does ...

![es-domain-https-only](https://user-images.githubusercontent.com/224732/71603466-bf2c2080-2b11-11ea-8019-3d16a2395746.png)

## Suggest specific test cases

1. if `true`, enforcement is on
2. if `false`, enforcement is off
3. if not mentioned, enforcement is whatever the default setting is (I assume it's off, but the docs don't seem to explicitly state this)

## Helpful Links to speed up research and evaluation

1. Feature described in service docs: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-data-protection.html
2. Release Notes showing the addition of the feature to the service back in October 2019: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/release-notes.html
3. The elasticsearch domain cfn resource docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html

## Category

Analytics
Security

**Comment by ueokande** [comment]
duplicated #201

**Comment by rhbecker** [comment]
Yep, you're right @ueokande. I had searched for existing ElasticSearch Domain issues, but used a flawed string (one colon instead of two). Thanks for finding / connecting.
