### ISSUE TITLE
AWS::WAFRegional::WebACL GovCloud

### ISSUE THREAD

**Issue by cmckni3** [aws-cloudformation/aws-cloudformation-coverage-roadmap#333]
## 2. Scope of request 

The following resource types should exist in GovCloud:

* AWS::WAFRegional::WebACL
* AWS::WAFRegional::WebACLAssociation
* AWS::WAFRegional::ByteMatchSet
* AWS::WAFRegional::GeoMatchSet
* AWS::WAFRegional::IPSet
* AWS::WAFRegional::RegexPatternSet
* AWS::WAFRegional::SizeConstraintSet
* AWS::WAFRegional::SqlInjectionMatchSet
* AWS::WAFRegional::XssMatchSet
* AWS::WAFRegional::RateBaseRule
* AWS::WAFRegional::Rule

## 3. Expected behavior

In Create, AWS::WAFRegional::WebACL should create instead of saying the resource type is not available.

## 4. Suggest specific test cases

I am using WAF for blocking requests to ALBs.

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

4.  Networking & Content (VPC, Route53, API GW,...)

**Comment by cmckni3** [comment]
WAFv2 is available in GovCloud.

I switched over to WAFv2 which allows the creation of Cloudfront or Regional WAF WebACL via the `Scope` property.

**Comment by bgardner-noggin** [comment]
Could the following also be added in this issue

AWS::WAFRegional::ByteMatchSet
AWS::WAFRegional::IPSet
AWS::WAFRegional::Rule

**Comment by cmckni3** [comment]
@bgardner-noggin done.

I suspect WAFv2 may be favored over WAFRegional.

**Comment by cmckni3** [comment]
Add the rest of the missing resource types.

**Comment by cmckni3** [comment]
WAFv2 appears to be the direction to move towards. The CFN spec for WAFv2 appears to be stable now.

Closing
