### ISSUE TITLE
AWS::KMS::Key asymmetric signing key support

### ISSUE THREAD

**Issue by abiro** [aws-cloudformation/aws-cloudformation-coverage-roadmap#337]
# AWS::KMS::Key asymmetric signing key support

## 2. Scope of request 

The `AWS::KMS::Key` resource doesn't support creating an asymmetric signing key today, although it is possible to create such a key through the KMS API.

This needs two things:

1. Support for `AWS::KMS::Key-CustomerMasterKeySpec` attribute
1. Support for `SIGN_VERIFY` value in `AWS::KMS::Key-KeyUsage` attribute (docs say this is supported, but it gives an error.)

## 5. Helpful Links to speed up research and evaluation

[AWS::KMS::Key resource doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html#cfn-kms-key-keyusage)
[KMS CreateKey API doc](https://docs.aws.amazon.com/kms/latest/APIReference/API_CreateKey.html#KMS-CreateKey-request-CustomerMasterKeySpec)
[StackoverFlow Question](https://stackoverflow.com/q/59633641/2650622)

## 6. Category (required) 

8. Security (IAM, KMS...)

**Comment by benkehoe** [comment]
I think I would prefer this be a separate resource type, perhaps even going so far as to separate out SIGN_VERIFY and ENCRYPT_DECRYPT asymmetric keys into separate types, so that it will be easier for type-checking tools to understand if they are being used correctly, audit tools to understand the contents of a template more simply, etc.

**Comment by okgolove** [comment]
Any chances this will be implemented? 🚀

**Comment by PatMyron** [comment]
[`AWS::KMS::Key`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html) is now open source and changes can be tracked here: https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-kms/tree/master/key

**Comment by ammokhov** [comment]
> Any chances this will be implemented? 🚀

this is currently WIP; should be merged soon - https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-kms/pull/24

**Comment by mkamioner** [comment]
Any update on this?

**Comment by jtcul** [comment]
> Any update on this?

Hey! This change is merged and should be available for use now. For more information, see the [AWS::KMS::Key](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html#cfn-kms-key-keyspec) documentation.
