### ISSUE TITLE
AWS::SES::ConfigurationSet

### ISSUE THREAD

**Issue by babulal049** [aws-cloudformation/aws-cloudformation-coverage-roadmap#342]
Currently AWS::SES::ConfigurationSet resource type cannot be created via CFN in eu-central-1a region.

Experiencing the following error while creating:

An error occurred (ValidationError) when calling the CreateChangeSet operation: Template format error: Unrecognized resource types: [AWS::SES::ConfigurationSet]

Sample code that can be used to create the resource via CFN:
```
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SesConfigSet:
    Type: AWS::SES::ConfigurationSet
    Properties:
      Name: 'config-set-test'
```

**Comment by PatMyron** [comment]
going to merge this issue into https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/326#issuecomment-571202255
