### ISSUE TITLE
AWS::DataSync::*

### ISSUE THREAD

**Issue by ngamradt-turner** [aws-cloudformation/aws-cloudformation-coverage-roadmap#343]
# Scope of request

There is no CloudFormation support for AWS DataSync:

https://aws.amazon.com/datasync/

# Expected behavior

CloudFormation support should have parity with what can be done in the AWS CLI:

https://docs.aws.amazon.com/cli/latest/reference/datasync/index.html

**Comment by ciaranevans** [comment]
Would love this! 👍

**Comment by dxciberaws** [comment]
+1

**Comment by stijnvanrenterghem** [comment]
+1

**Comment by rsimonfr** [comment]
+1 and add also registration  for Private Agent   the work done by curl "http://agent-ip-address/?gatewayType=SYNC&activationRegion=region&privateLinkEndpoint=EIP&endpointType=PRIVATE_LINK&no_redirect"
 to retrieve the Registration ID

**Comment by githubnoobieme** [comment]
+1

**Comment by benbridts** [comment]
@ciaranevans @dxciberaws @rsimonfr @githubnoobieme 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

**Comment by gamma425** [comment]
any timeline for this?

**Comment by ibuys** [comment]
Hoping to see CF support for DataSync soon. Would be great for automated scheduled sync S3 -> EFS.

**Comment by rohits-spec** [comment]
The support for Datasync was introduced on 1/7/2021. Closing this issue.
