### ISSUE TITLE
AWS:CUR::ReportDefintion

### ISSUE THREAD

**Issue by tobilg** [aws-cloudformation/aws-cloudformation-coverage-roadmap#347]
## 1. Title 
AWS:CUR::ReportDefintion

## 2. Scope of request 
Coverage of CRUD actions on the Cost and Usage Report's ReportDefinition resource, which is not yet available via CloudFormation.

## 5. Helpful Links to speed up research and evaluation
See API docs:

* https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_Operations_AWS_Cost_and_Usage_Report_Service.html

## 6. Category
11. Other (IoT, Migration, Budgets...)

**Comment by PatMyron** [comment]
merging into https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/316
