### ISSUE TITLE
Re-evaluate Limits

### ISSUE THREAD

**Issue by ngamradt-turner** [aws-cloudformation/aws-cloudformation-coverage-roadmap#360]
## Scope of request 

Per the documentation, there is a limit of 60 parameters per template:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html

## Expected behavior

The 60 parameter limit appears to be arbitrary and often causes problems with complex templates or with resources that may require a large number of parameters (for instance, a large number of environment variables needed for an ECS task definition).

We would like to see this number either doubled to 120 parameters per template or eliminated all together.  At 120 parameters, this problem would occur much less frequently and the case could probably me made more often that a refactor could eliminate the issue, but at 60 parameters, we run into it often due to us wanting to make templates more reusable.  Some resources have a lot of options that need to be accounted for.

It should also be noted that the lack of a "latest" option for SSM parameters when using Dynamic references makes them much less useful than they could be, otherwise these could be used to reduce the need for parameters:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html

**Comment by PatMyron** [comment]
Going to generalize this issue since most of [CloudFormation's limits](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html) should be re-evaluated

**Comment by benkehoe** [comment]
Separate from simply more parameters, the ability to use (and validate) JSON objects as parameters would enable a lot more information to be injected into templates with better semantics. Should I open that as a separate issue?

**Comment by ngamradt-turner** [comment]
@PatMyron Okay, if this is going to become a general-purpose ticket about limits, then let me add another one:

For the "AWS::CodePipeline::Pipeline" resource, there are 1000 character limits for things such as...

1. ParameterOverrides (for CloudFormation)
2. EnvironmentVariables (for CodeBuilds)

Again, these limits seem odd, depending on variable name lengths, these limits are easy to hit for fairly normal implementations.

**Comment by trav-c** [comment]
@PatMyron 

Here's another on I seem to hit not too infrequently:
 [AWS::Lambda::Function.Code.ZipFile](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html#cfn-lambda-function-code-zipfile) is limited to 4096 bytes.

It's pretty easy to hit that when putting together custom resources to handle not yet supported by CloudFormation resource types when you are trying to keep some resources inline in templates for portability, especially if you are trying to keep code readable, obviously after a certain size it usually doesn't makes much sense to keep the code inline in the template, but in my experience that threshold is more than 4 kiB and it would greatly increase the utility if the limit could be increased to something in the 8 kB+ range.

**Comment by ngamradt-turner** [comment]
@PatMyron I have sent you an example over Slack, please take a look and let me know what further details you need from me regarding the `EnvironmentVariables` limit.

**Comment by PatMyron** [comment]
@ngamradt-turner this error is being thrown by CodePipeline, not CloudFormation:
```
1 validation error detected: Value at 'pipeline.stages.3.member.actions.1.member.configuration' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 1000, Member must have length greater than or equal to 1] (Service: AWSCodePipeline; Status Code: 400; Error Code: ValidationException; Request ID: REDACTED)
```
CloudFormation cannot unilaterally bypass the underlying service's limits

**Comment by ikben** [comment]
@kteague the total number of stacks is a soft limit you can increase within the Service Quotas service.

**Comment by josb** [comment]
Any updates on this, especially on raising the 60-parameters-per-stack limit? Or, can you at least give us some insight into why raising this limit isn't trivial? Please?

**Comment by luiseduardocolon** [comment]
@josb Hi there.  We are making good progress on this.  Stay tuned.

**Comment by josb** [comment]
@luiseduardocolon thanks for the update! Waiting patiently...

**Comment by jdub** [comment]
My favourite disappointing CloudFormation limit is DetectStackDrift. I created a Config rule to detect drift every 3 hours and on stack changes, but with 110+ stacks in our test account, it always throttles and fails. 😢 (See case ID 6832938811.)

**Comment by PatMyron** [comment]
**[AWS CloudFormation now supports increased limits on five service quotas](https://aws.amazon.com/about-aws/whats-new/2020/10/aws-cloudformation-now-supports-increased-limits-on-five-service-quotas/)**

> The maximum size of a template that can be passed in an S3 Object is now 1MB (previously 450KB). The new per template limits for the maximum number of resources is 500 (previously 200), parameters is 200 (previously 60), mappings is 200 (previously 100), and outputs is 200 (previously 60)

**Comment by josb** [comment]
Thanks @PatMyron! Appreciate the 140 extra stack parameters!

**Comment by luiseduardocolon** [comment]
Shipped and closing.

**Comment by PatMyron** [comment]
**[AWS CloudFormation now supports more stacks per AWS account](https://aws.amazon.com/about-aws/whats-new/2021/06/aws-cloudformation-now-supports-more-stacks-per-aws-account/)**

>AWS CloudFormation now supports increased limits on the default number of stacks allowed per AWS account. The number of stacks that can be created in an account is now 2000 (previously 200).
