### ISSUE TITLE
CloudFormation Support for AWS::DataSync::*

### ISSUE THREAD

**Issue by ngamradt-turner** [aws-cloudformation/aws-cloudformation-coverage-roadmap#361]
## 1. Title 

AWS::DataSync::*

## 2. Scope of request 

All of the functionality that is supported by the AWS DataSync API needs to be supported by CloudFormation:

https://docs.aws.amazon.com/cli/latest/reference/datasync/index.html

## 3. Expected behavior

I should be able to create AWS DataSync resources in CloudFormation.

## 4. Suggest specific test cases

Create AWS resources using the CLI and then do the same thing using CloudFormation, the results should match.

## 5. Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/cli/latest/reference/datasync/index.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Use the categories as displayed in the AWS Management Console (simplified):

Storage (S3, EFS, Backup...)

**Comment by PatMyron** [comment]
Merging into https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/343
