### ISSUE TITLE
AWS::Route53::RecordSet

### ISSUE THREAD

**Issue by OlafConijn** [aws-cloudformation/aws-cloudformation-coverage-roadmap#364]
AWS::Route53::RecordSet does not handle changing the logicalName of the resource correctly.

**problem**:
If I change the logicalName of a AWS::Route53::RecordSet resource (without changing any attribute) this will result in the Record being deleted.

looking at the events in cloudwatch it seems that:
- the resource with the new logicalName gets created before the resource with the old logicalName gets deleted
- when the resource with the old logicalName gets deleted both records are gone!

**Expected behavior** is that the record stays after rename

**Test case**
create a stack using
```
  ParentNsRecord:
    DependsOn: RootHostedZone
    Type: AWS::Route53::RecordSet
    Properties:
      Type: NS
      HostedZoneName: !Sub '${rootHostedZoneName}.'
      Name: !Sub '${subdomain}.${rootHostedZoneName}.'
      TTL: 86400
      ResourceRecords: !GetAtt nameServers
```
update the stack using 
```
  ParentNsRecord2:
    DependsOn: RootHostedZone
    Type: AWS::Route53::RecordSet
    Properties:
      Type: NS
      HostedZoneName: !Sub '${rootHostedZoneName}.'
      Name: !Sub '${subdomain}.${rootHostedZoneName}.'
      TTL: 86400
      ResourceRecords: !GetAtt nameServers
```

**Comment by PatMyron** [comment]
merging these two Logical ID renaming behavior issues together
