### ISSUE TITLE
AWS::EC2::Subnet-OutpostArn

### ISSUE THREAD

**Issue by FireballDWF** [aws-cloudformation/aws-cloudformation-coverage-roadmap#377]
Support passing the OutpostArn attribute when calling CreateSubnet https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateSubnet.html

**Comment by adam-imeson** [comment]
For cloudformation to support Outposts, we need to add the OutpostArn attribute for everything that launches using an OutpostArn attribute. I don't know the full list, but in addition to subnets it includes EBS volumes: https://docs.aws.amazon.com/cli/latest/reference/ec2/create-volume.html

**Comment by FireballDWF** [comment]
Resolved awhile ago
