### ISSUE TITLE
AWS::Cognito::UserPool-UsernameConfiguration add to support case insensitive usernames

### ISSUE THREAD

**Issue by kziemski** [aws-cloudformation/aws-cloudformation-coverage-roadmap#378]
Cognito UserPools CreateUserPool API just released the ability to specify that username aliases be case insensitive. 
Huge benefit because it prevents issues with email used as user names that are capitalized and Cognito treating them as different user names.

[https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateUserPool.html#CognitoUserPools-CreateUserPool-request-UsernameConfiguration](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateUserPool.html#CognitoUserPools-CreateUserPool-request-UsernameConfiguration)

Ideally it should match to the API Reference based on how you have UserPool currently.
AWS::Cognito::UserPool
      UsernameConfiguration:
            CaseSensitive: Boolean

Thank you this is would be much appreciated bc UserPools are Immutable once created so i can't change this options after its created in the console or via API

**Comment by dennisroche** [comment]
This appears to have been done?

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-usernameconfiguration

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-usernameconfiguration.html


A little bit annoying as just finished creating a custom resource to support this property.

**Comment by kziemski** [comment]
ty for pointing this out. trying it in my next refresh.
