### ISSUE TITLE
AWS::ACM::PCA - New Resource

### ISSUE THREAD

**Issue by dataGeeek** [aws-cloudformation/aws-cloudformation-coverage-roadmap#38]
Title -> AWS::ACM::PCA
Scope of request -> Manages an ACM Private CA Resource
Expected behavior -> Create, Update and Delete a Private CA
Test case recommendation (optional) ->
Links to existing API doc (optional) -> https://docs.aws.amazon.com/acm-pca/latest/APIReference/API_CreateCertificateAuthority.html
Category tag (optional) -> ACM

**Comment by ab77** [comment]
In the meantime: https://github.com/ab77/cfn-generic-custom-resource/tree/master/acm-pca

**Comment by luiseduardocolon** [comment]
See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_ACMPCA.html this work has been completed :)
