### ISSUE TITLE
AWS::DynamoDB::GlobalTable - New Resource

### ISSUE THREAD

**Issue by rshayman** [aws-cloudformation/aws-cloudformation-coverage-roadmap#380]
## Instructions for CloudFormation Coverage New Issues Template

Quick Sample Summary:
1. Title -> AWS::DynamoDB::GlobalTable - New Resource
2. Scope of request -> Add support for Global Tables
3. Expected behavior -> Global tables are created in a number of additional regions
4. Test case recommendation (optional) -> 
5. Links to existing API doc (optional) -> Add a new page under https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_DynamoDB.html
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.create_global_table
6. Category tag (optional) -> Database
7. Any additional context (optional)

GlobalTable:
    Type: AWS::DynamoDB::GlobalTable
    Properties:
        GlobalTableName: !Ref Table
        ReplicationRegions:
            - us-east-1
            - us-west-2

Would be more useful than as a StringList parameter could be used

GlobalTable:
    Type: AWS::DynamoDB::GlobalTable
    Properties:
        GlobalTableName: !Ref Table
        Replication:
            - Region: us-east-1
            - Region: us-west-2

**Comment by PatMyron** [comment]
Merging into https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/57
