### ISSUE TITLE
Feature Request: Add EFS support for AWS CodeBuild using CloudFormation

### ISSUE THREAD

**Issue by NujellaKarthik** [aws-cloudformation/aws-cloudformation-coverage-roadmap#381]
Feature Request: Add EFS support for AWS CodeBuild using CloudFormation

https://aws.amazon.com/about-aws/whats-new/2020/02/aws-codebuild-adds-support-for-amazon-efs/

**Comment by luiseduardocolon** [comment]
Duplicate of #374 - closing
