### ISSUE TITLE
AWS::EFS::FileSystem expand region availibility

### ISSUE THREAD

**Issue by giliamv** [aws-cloudformation/aws-cloudformation-coverage-roadmap#389]
## AWS::EFS::FileSystem expand region availibility

As of Feb 5, 2020 Amazon Elastic File System (EFS) is now available in the AWS GovCloud (US-East) Region:
https://aws.amazon.com/about-aws/whats-new/2020/02/amazon-elastic-file-system-amazon-efs-is-now-available-in-the-aws-govcloud-us-east-region/

CloudFormation currently returning "Resource is not supported in this region" when trying to create AWS::EFS::FileSystem in us-gov-east-1.

**Comment by abierbaum** [comment]
This there any way to work around this in the meantime?  This is causing major problems for our deployments that need GovCloud support.

**Comment by rohits-spec** [comment]
CFN support for EFS is available in the Govcloud regions. Closing this issue. Please reopen if there's anything missing.
