### ISSUE TITLE
AWS::CodeBuild::ReportGroup Delete

### ISSUE THREAD

**Issue by fimbulvetr** [aws-cloudformation/aws-cloudformation-coverage-roadmap#390]
It should be possible for CF to delete a report group, even if it has report groups in it. 

I understand there is some attempt to preserve the data but a CF delete really should be honored. Even deleting an SSM Secret is supported by CloudFormation, and that would seem to be much more important than some codebuild reports.

Right now if I have hundreds and hundreds of reports I have to delete them manually before I can delete the CF stack. FYI the API does not offer very good support for deleting hundreds of reports.

**Comment by luiseduardocolon** [comment]
not familiar with that particular downstream API... is there an API call that supports such a delete?

**Comment by fimbulvetr** [comment]
@luiseduardocolon Yes, there is https://docs.aws.amazon.com/codebuild/latest/APIReference/API_BatchDeleteBuilds.html

**Comment by akritibhat** [comment]
https://docs.aws.amazon.com/cli/latest/reference/codebuild/delete-report-group.html

**Comment by akritibhat** [comment]
this has been updated and allows to delete report group with reports

**Comment by fimbulvetr** [comment]
Thanks, works well.
