### ISSUE TITLE
AWS::EFS::AccessPoint

### ISSUE THREAD

**Issue by mildebrandt** [aws-cloudformation/aws-cloudformation-coverage-roadmap#395]
## 1. Title 
AWS::EFS::AccessPoint

## 2. Scope of request 
AWS::EFS::AccessPoint - Can create an access point from the API, but not via CF

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1
2. Storage (S3, EFS, Backup...)

**Comment by day1118** [comment]
Is there a timeline for this feature? The [FARGATE support for EFS](https://aws.amazon.com/about-aws/whats-new/2020/04/amazon-ecs-aws-fargate-support-amazon-efs-filesystems-generally-available/) looks very useful, but I cannot see how this can be done using CFT without this feature as you must create the access point outside of CFT which defeats the purpose.

**Comment by craigataws** [comment]
In process of being released

**Comment by craigataws** [comment]
Released on June 2, 2020
