### ISSUE TITLE
AWS::Glue::Workflow - New Resource

### ISSUE THREAD

**Issue by dataGeeek** [aws-cloudformation/aws-cloudformation-coverage-roadmap#40]
Title -> AWS::Glue::Workflow
Scope of request -> Manages Glue Workflow Resources
Expected behavior -> Create, Update and Delete Glue Workflows
Test case recommendation (optional) ->
Links to existing API doc (optional) -> https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-workflow.html
Category tag (optional) -> Glue

**Comment by TheDanBlanco** [comment]
Just checking, you mean AWS::Glue::Workflow, right?

**Comment by dataGeeek** [comment]
@TheDanBlanco exactly

**Comment by TheDanBlanco** [comment]
👍

**Comment by pbsinclair42** [comment]
Looks like this is now supported: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-workflow.html
