### ISSUE TITLE
AWS::Athena::*

### ISSUE THREAD

**Issue by andromeda306** [aws-cloudformation/aws-cloudformation-coverage-roadmap#409]
Scope of request -> Presently the only Athena related Cloudformation resource that exists is AWS::Athena::NamedQuery. Ideally a resource should exist for all of the commands made available via the aws-cli similar as is the case with AWS::Glue, its seems somewhat arbitrary and frustrating that only the NamedQuery command should exist with no other options.

Expected behavior -> Using stacks I should be able to create/modify/destroy all the resources made available within Athena, as well as have access to the same resource properties. Presently this functionality is absent or works inconsistently. For example there are discrepancies between available properties for the NamedQuery resource in Cloudformation, in contrast to those available when using aws-cli. In another case, NamedQueries created via Cloudformation cannot be deleted programatically despite the stack being successfully destroyed, as a result they have to be manually removed one-by-one via the GUI.

Links to existing API doc -> 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Athena.html
https://docs.aws.amazon.com/cli/latest/reference/athena/index.html#cli-aws-athena
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Glue.html
https://docs.aws.amazon.com/cli/latest/reference/glue/index.html#cli-aws-glue

Category tag (optional) -> Analytics

**Comment by PatMyron** [comment]
See the recently launched [`AWS::Athena::WorkGroup` support](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/90)

[`AWS::Athena::WorkGroup` documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-athena-workgroup.html)

[CloudFormation release history](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html)

**Comment by luiseduardocolon** [comment]
It looks like, per the CLI commands available, that CRUD exists now for named queries and work groups.  Since no other entities can be CRUD'ed, I'll close this for now and mark it as shipped.
