### ISSUE TITLE
AWS::CloudFront::Distribution S3 Bucket policy

### ISSUE THREAD

**Issue by akshayvvr** [aws-cloudformation/aws-cloudformation-coverage-roadmap#413]
## Support for Changing bucket policy on creation of Cloudfront OAI config

Quick Sample Summary:
1. Title -> AWS::CloudFront::Distribution

2. Scope of request -> AWS::CloudFront::Distribution::DistributionConfig::Origins::S3OriginConfig-Existing supports linking a CDN OAI [Origin Access Identity] and not updating the s3 bucket policy. 

3. Expected behavior -> 

Just like the AWS console, Where there is an option to update the bucket policy. It would be great if Cloudformation supports that. 

4. Links to existing API doc (optional) -> 

- [https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html#private-content-creating-oai](url)

5. Category tag (optional) -> Networking & Content

**Comment by ikben** [comment]
Hey @akshayvvr,

Is there a reason that you prefer this over managing the full bucket policy in CloudFormation?

**Comment by TheDanBlanco** [comment]
i'm with @ikben on this one - this seems like it's entirely possible to manage through cloudformation

**Comment by arnesolheim** [comment]
Too bad this one was closed; Use case: If the bucket (and its policy) was created (and maintained) in one stack, and the cloudfront distro in another stack then it would be a kind of a catch22; you would not know about the OAI at the point in time when you created the S3 bucket, and you would not have the possibility to automatically update it afterwards through the stack in which you created the cloudfront distro.
