### ISSUE TITLE
AWS::Events::Bus - New Resource

### ISSUE THREAD

**Issue by jk2l** [aws-cloudformation/aws-cloudformation-coverage-roadmap#42]
CloudWatch Event recently got rebranded as EventBridge and introduced new dedicated EventBus.

When create a new Event Bus should be created.
When update existing Bus should raise Error
When delete the Bus should be deleted unless there is event rule attached to it

https://docs.aws.amazon.com/cli/latest/reference/events/index.html#cli-aws-events

Category: Integration (AWS EventBus)

**Comment by jk2l** [comment]
Tried to attach category "Integration" into this issue but i can't find any way for me to add category

**Comment by iann0036** [comment]
Should probably be under `AWS::Events` to match the others in EventBridge.

**Comment by rohits-spec** [comment]
This has been addressed https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-eventbus.html .
