### ISSUE TITLE
AWS::Events::Rule - New Attribute (Event Bus Name)

### ISSUE THREAD

**Issue by jk2l** [aws-cloudformation/aws-cloudformation-coverage-roadmap#44]
This new attribute introduced with AWS EventBridge. You can now create a new dedicated Event Bus for handling event and you can also attach Rule to it. By default if event-bus-name is missing from parameter. It will be attach to CloudWatch default Bus.

On create/update with the event-bus-name it should attach to the Event Bus specified
On create/update without event-bus-name it should attach to the default Bus

https://docs.aws.amazon.com/cli/latest/reference/events/put-rule.html

Category: Integration (AWS EventBus)

**Comment by iann0036** [comment]
Should be `AWS::Events::Rule`.

**Comment by rohits-spec** [comment]
This issue has been addressed. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-eventbus.html
