### ISSUE TITLE
AWS::ECS::TaskDefinition-Volume-EfsVolumeConfiguration

### ISSUE THREAD

**Issue by autarchprinceps** [aws-cloudformation/aws-cloudformation-coverage-roadmap#440]
## 1. Title 
AWS::ECS::TaskDefinition-Volume-EfsVolumeConfiguration

## 2. Scope of request 
   c) new attribute for an existing resource is desired:
New feature AWS::ECS::TaskDefinition-Volume-EfsVolumeConfiguration is missing from CloudFormation, but implemented in ECS API.

## 3. Expected behavior
Implementing this in the Cloudformation creation of TaskDefinition: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/efs-volumes.html

## 4. Suggest specific test cases
Using storage from within Fargate.

## 5. Helpful Links to speed up research and evaluation
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/efs-volumes.html
https://aws.amazon.com/about-aws/whats-new/2020/04/amazon-ecs-aws-fargate-support-amazon-efs-filesystems-generally-available/

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1
Compute

**Comment by michaelwittig** [comment]
is this a duplicate of #418 ?

**Comment by autarchprinceps** [comment]
Kind of. The implementation probably is the same, though the reason isn't. This one was for Fargate EFS support, the other one only for standard ECS.

**Comment by jupeter** [comment]
Looks like duplicate of #418. Propose close this and continue work on previous.

**Comment by luiseduardocolon** [comment]
@jupeter you are correct, closing this one and 418 - got recently deployed :)
