### ISSUE TITLE
AWS::Serverless::HttpApi - DefinitionUri - no transform

### ISSUE THREAD

**Issue by jvroig** [aws-cloudformation/aws-cloudformation-coverage-roadmap#444]
In **AWS::Serverless::HttpApi**, DefinitionUri is not being transformed by the "package" command from local path to S3 path. (Note, this is "HttpApi", which is relatively new). This results in the error " 'DefinitionUri' is not a valid S3 Uri of the form 's3://bucket/key' with optional versionId query parameter." in my CI/CD pipeline, since the local path was untouched.

Expected behavior: Similar to the old REST API resource [AWS::Serverless:Api] local path should be transformed to S3 path.

The relevant documentation for HttpApi confirms that this is the desired behavior. See the "DefinitionUri" section in its documentation page: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-httpapi.html#sam-httpapi-definitionuri

Thanks, CloudFormation team!

EDIT: Closing - I just realized I posted this in the wrong repo. Will transfer this to the **cloudformation-cli** repo. Apologies.

**Comment by yvele** [comment]
Note for Googlers: The issue has been created here https://github.com/aws-cloudformation/cloudformation-cli/issues/420 but should have been created in aws-sam-cli -> https://github.com/aws/aws-sam-cli/issues
