### ISSUE TITLE
AWS::AppFlow::NewService - Cannot create AppFlow from CF

### ISSUE THREAD

**Issue by gpongracz** [aws-cloudformation/aws-cloudformation-coverage-roadmap#454]
Scope of request: new service support is desired for Amazon AppFlow
Expected behaviour: It should replicate capability currently on offer via Amazon AppFlow console at https://console.aws.amazon.com/appflow/
It should **enable the wildcarding** of source objects eg: salesforce objects to avoid having to specify each object specifically and to facilitate simple rerun to capture any new objects available in service catalog
Category: 9. Integration
Helpful Links: https://docs.aws.amazon.com/appflow/latest/userguide/flows.html

**Comment by parsnips** [comment]
Would love for this to be supported!

**Comment by vinaykondapi** [comment]
Hi All, 
Thank you for your feedback. We will look into your request on enabling wildcarding. Also, we are excited to announce that Amazon AppFlow now support AWS CloudFormation. What’s new: https://aws.amazon.com/about-aws/whats-new/2020/09/amazon-appflow-now-supports-aws-cloudformation/ Documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_AppFlow.html. Please let us know if you have any additional feedback. 
Thanks,
Vinay.

**Comment by gpongracz** [comment]
Thank you CF team for your work on this, your effort is appreciated and the
capability is valuable to us.

Regards,

George Pongracz

**Comment by kromol** [comment]
Also `idFieldNames` and `writeOperationType` from [SalesforceDestinationProperties](https://docs.aws.amazon.com/appflow/1.0/APIReference/API_SalesforceDestinationProperties.html) are currently not available in CloudFormation.

**Comment by oxygenecore** [comment]
I've created a flow using Cloudformation, but it's in the Draft stage. Also, I can not open it in the AWS Console (I'm getting error `Cannot read property 'DATA_TYPE' of undefined`).

**Comment by ejunker** [comment]
@oxygenecore I have a similar problem with my flow created with CF is in the Draft stage. My flow is using a Scheduled trigger but if I created it with TriggerType: OnDemand it showed as Active.

**Comment by tusharpandit18** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/34574
