### ISSUE TITLE
Cloudformation CodePipeline Action should emit stack outputs as pipeline variables

### ISSUE THREAD

**Issue by x6j8x** [aws-cloudformation/aws-cloudformation-coverage-roadmap#455]
# 1. Title

Cloudformation CodePipeline Action should emit stack outputs as pipeline variables.

## 2. Scope of request 

Cloudformation Action for CodePipeline 

## 3. Expected behavior

When defining a _Namespace_ on a Cloudformation Action (ActionModes: CREATE_UPDATE, CHANGE_SET_EXECUTE, REPLACE_ON_FAILURE) in a CodePipeline pipeline, it should provide all output values of the stack created by that action back to the pipeline. 

Currently, we're using a CodeBuild action to bounce stack outputs back to the pipeline for further use (ApiGateway Ids, SQS queue URLs, ...). In this action, we use `aws cloudformation describe-stacks` to discover the outputs, then export the output values as environment variables and use the `exported-variables` buildspec feature to expose these values back to the pipeline. 

This is rather tedious as it involves adding additional CodeBuild specs all over the place.

## 4. Suggest specific test cases

Create a stack with an API gateway, output it's _RestApiId_, and then run post-deployment validations against it in the pipeline without needing to manually access the stack outputs. 

## 5. Helpful Links to speed up research and evaluation

- CodePipeline - Working with Variables (https://docs.aws.amazon.com/codepipeline/latest/userguide/actions-variables.html)
- CodePipeline - Cloudformation Action (https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CloudFormation.html)

## 6. Category (required)

Developer Tools

**Comment by jk2l** [comment]
This can be useful if pipeline can store in internal state. I have set up a cross-account pipeline that CI/CD account can deploy into target account, but for CloudFormation to write it back as Output artifact it will need to grant target account write permission. and this complicates the whole bucket policy and permission setup

**Comment by luiseduardocolon** [comment]
We believe this is available now.  Ping us if you think we need to reopen.

**Comment by entest-hai** [comment]
I am still not able to get this working
```
An action in this pipeline failed because one or more variables could not be resolved
```

**Comment by JeremieRodon** [comment]
@entest-hai I'm guessing you are also using an OutputArtifact with the `Configuration.OutputFileName` node.

My tests shows that the `Namespace` parameter is completely ignored by the CloudFormation deploy action if there is an output artifact containing the stack outputs in a file using the `Configuration.OutputFileName` node.
But I can also confirm that `Namespace` behaves as expected when the CloudFormation deploy action does not produce an output artifact.

I suppose there is a reason for this behavior, but I was not able to find an appropriate documentation.
