### ISSUE TITLE
AWS::ECS::Service-NewAttribute-CapacityProviderStrategy

### ISSUE THREAD

**Issue by JohnPreston** [aws-cloudformation/aws-cloudformation-coverage-roadmap#459]
## 2. Scope of request 

New feature for ECS Service which is available via API [ecs.create_service](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html#ECS.Client.create_service) should allow to be supported in CloudFormation too.

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1
1. Compute - ECS - Fargate/FargateSpot - ASG

**Comment by iann0036** [comment]
@luiseduardocolon this doesn't appear in the docs, can you confirm?

**Comment by anoopkapoor** [comment]
CapacityProviderStrategy is now available in the AWS::ECS::Service resource.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html

**Comment by JohnPreston** [comment]
:+1: So happy to see this came through.
Thank you so much @luiseduardocolon and AWS Team for making it happen.
