### ISSUE TITLE
AWS::S3::Bucket NotificationConfiguration - Add support for existing buckets

### ISSUE THREAD

**Issue by TonyFNZ** [aws-cloudformation/aws-cloudformation-coverage-roadmap#466]
## 1. Title 
AWS::S3::Bucket NotificationConfiguration - Add support for existing buckets

## 2. Scope of request 
AWS::S3::Bucket NotificationConfiguration can only be set in the CFN template that created the target S3 bucket.  A new resource type should be created so that NotificationConfiguration can be updated on an existing bucket.

## 3. Expected behavior
There is an existing CloudFormation Custom Resource (see link below) which supports this usecase, however a new resource type should be added so that it is possible to do this in vanilla CloudFormation without requiring the clutter of having lots of custom resources defined.

Ideally this resource would not overwrite other notification configuration which already exists on the target bucket.

## 4. Suggest specific test cases
This will allow Lambda functions to be created and subscribed to S3 events without requiring the Lambda function and notification configuration to be defined in the same template as the target S3 bucket.

## 5. Helpful Links to speed up research and evaluation
Existing Custom Resource which implements this functionality
https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-s3-notification-lambda/

CDK issue which is blocked by this issue: https://github.com/aws/aws-cdk/issues/4323

## 6. Category
2. Storage (S3, EFS, Backup...)

**Comment by purnesh** [comment]
+1

**Comment by benkehoe** [comment]
This has already been raised as issue #79. It's a problem that notification configuration isn't a separate resource even when the bucket is in the same stack.

**Comment by TonyFNZ** [comment]
Thanks @benkehoe.  I tried to search for existing issues, but didn't find that one.  Closing this as duplicate
