### ISSUE TITLE
AWS::Serverless::Api - AuthorizerResultTtlInSeconds

### ISSUE THREAD

**Issue by furuton** [aws-cloudformation/aws-cloudformation-coverage-roadmap#470]
## 1. Title 

AWS::Serverless::Api - AuthorizerResultTtlInSeconds

## 2. Scope of request 

I want to set AuthorizerResultTtlInSeconds using AWS::Serverless::Api to disable Authorizer cache((Default is enabled cache)
But AWS::Serverless::Api doesn't support setting AuthorizerResultTtlInSeconds.

I know that AWS::ApiGateway::Authorizer supports AuthorizerResultTtlInSeconds.
But I want to only use SAM template.
So I request that AWS::Serverless::Api supports setting AuthorizerResultTtlInSeconds.

## 3. Expected behavior

AWS::Serverless::Api can set AuthorizerResultTtlInSeconds.

## 4. Suggest specific test cases

+ Set authorizerResultTtlInSeconds 
+ Disable Authorizer cache(if authorizerResultTtlInSeconds = 0)

## 5. Helpful Links to speed up research and evaluation

Authorizer - Amazon API Gateway API Reference
https://docs.aws.amazon.com/apigateway/api-reference/resource/authorizer/#authorizerResultTtlInSeconds

```
authorizerResultTtlInSeconds

The TTL in seconds of cached authorizer results. If it equals 0, authorization caching is disabled. If it is greater than 0, API Gateway will cache authorizer responses. If this field is not set, the default value is 300. The maximum value is 3600, or 1 hour.
```

AWS::Serverless::Api - AWS Serverless Application Model
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html

AWS::ApiGateway::Authorizer - AWS CloudFormation
https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-authorizer.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

4.  Networking & Content (VPC, Route53, API GW,...)

**Comment by PatMyron** [comment]
[`AWS::Serverless`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-resources-and-properties.html) requests might be better suited [here](https://github.com/awslabs/serverless-application-model/issues)

**Comment by furuton** [comment]
Thanks.
I created Github issue in  awslabs/serverless-application-model 

[[Feature request]AWS::Serverless::Api - AuthorizerResultTtlInSeconds](https://github.com/awslabs/serverless-application-model/issues/1593)

So I close this issue.
