### ISSUE TITLE
Support for cross-account delivery to ElasticSearch in resource AWS::KinesisFirehose::DeliveryStream.

### ISSUE THREAD

**Issue by bbergero** [aws-cloudformation/aws-cloudformation-coverage-roadmap#477]
1. Title -> AWS::KinesisFirehose::DeliveryStream
2. Scope of request -> The “ElasticSearchDestinationConfiguration” element in the resource does not provide all available options as found in the API and AWS CLI. Specifically, it does not allow the “ClusterEndpoint” attribute that is required to configure delivery to an ElasticSearch domain in a different account.

3. Expected behavior -> CFN service: “ElasticSearchDestinationConfiguration” element in the resource to provide all available options as found in the API and AWS CLI.

4. Test case recommendation (optional) -> 
5. Links to existing API doc (optional) -> https://docs.aws.amazon.com/firehose/latest/APIReference/API_ElasticsearchDestinationConfiguration.html 
6. Category tag (optional) -> Compute
7. Any additional context: This forces us to use methods out of CFN, such as Terrraform or scripts to create this type of resource, that is then managed out of the CFN stack lifecycle, or alternatively create a custom CFN resource that in this case would be one of unjustifiable high complexity considering it would have to implement 99% of the same features found in the existing stock one.

**Comment by craigataws** [comment]
Shipped on June 2, 2020
