### ISSUE TITLE
AWS::Cognito::UserPoolClient-AllowedOAuthFlowsUserPoolClient

### ISSUE THREAD

**Issue by benbridts** [aws-cloudformation/aws-cloudformation-coverage-roadmap#48]
AllowedOAuthFlowsUserPoolClient can be set by the API, but not with CloudFormation. It must be set to enable the OAuth flows and is needed for #47 

Create and Update are both supported without replacement.

https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateUserPoolClient.html#CognitoUserPools-CreateUserPoolClient-request-AllowedOAuthFlowsUserPoolClient

Category: Security, Identity, & Compliance

**Comment by nuttmeister** [comment]
Hey,

Please have a look at our custom resource for this:
https://github.com/dwtechnologies/custom-cf/tree/master/cognito/userpool-client

And us know if it doesn't work for your usecase and we would be happy to update it.

**Comment by brianterry** [comment]
Hello! 
This resource property is currently supported by CloudFormation.

Please see our docs for more details:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-allowedoauthflowsuserpoolclient
