### ISSUE TITLE
EFS FileSystem Policy support via CloudFormation

### ISSUE THREAD

**Issue by chaithanya25** [aws-cloudformation/aws-cloudformation-coverage-roadmap#481]
I would like to know about  how EFS policy that can be used to restrict access to users when access EFS via CloudFormation template. Currently, the policy is only supported via AWS console. I have verified the CloudFormation document, it's indeed not mentioning the EFS file system policy.
We have a requirement when in we use CFN's for updating policy of the user. It will be greatful if we get the feature enabled. So could you please let me know when can we have a feature for enabling EFS policy via CFN.

**Comment by luiseduardocolon** [comment]
So, something like AWS::EFS::FileSystem AccessPolicy [New Attribute]? 
Is the underlying API this one? 

https://docs.aws.amazon.com/efs/latest/ug/API_PutFileSystemPolicy.html

If so, adding this to the issue here makes it easier for other customers to discover and +1 your request, which in turn increases the likelihood of it being noticed sooner :)

Let us know here.

**Comment by chaithanya25** [comment]
Yes exactly, I have raised a support case for Amazon Support. (CASE 6864177981 : EFS Policy for Cloud Formation Templates) and I have received a response saying there is a feature request for enabling EFS policy via CFN which is on going. Could you please let me know when the feature can be expected. 
The underlying API is this as you have mentioned above:
https://docs.aws.amazon.com/efs/latest/ug/API_PutFileSystemPolicy.html.

Thank You!

**Comment by str3tch** [comment]
@chaithanya25 I think it is already supported?

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-efs-filesystem.html#cfn-efs-filesystem-filesystempolicy

**Comment by PatMyron** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html
