### ISSUE TITLE
AWS::Synthetics::Canary [Update Parameter]

### ISSUE THREAD

**Issue by craigataws** [aws-cloudformation/aws-cloudformation-coverage-roadmap#503]
Scope of request -> Update Parameter
Expected behavior -> I want the RunConfig parameter to be required
Category tag (optional) -> Management Tools

**Comment by craigataws** [comment]
Shipped on May 14, 2020

**Comment by pushthat** [comment]
Is it an expected behavior that the lambda used by the canary (and created by the canary resource) is not deleted on the deletion of the canary resource ?
