### ISSUE TITLE
AWS::CodeGuruProfiler::ProfilingGroup - AgentPermissions (new attribute)

### ISSUE THREAD

**Issue by luiseduardocolon** [aws-cloudformation/aws-cloudformation-coverage-roadmap#513]
## IAWS::CodeGuruProfiler::ProfilingGroup - AgentPermissions (new attribute)

2. Scope of request -> Support agent permissions attribute.

6. Category tag (optional) -> Dev Tools

**Comment by PatMyron** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codeguruprofiler-profilinggroup.html#cfn-codeguruprofiler-profilinggroup-agentpermissions

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html
