### ISSUE TITLE
AWS::CodeArtifact:* Service

### ISSUE THREAD

**Issue by fimbulvetr** [aws-cloudformation/aws-cloudformation-coverage-roadmap#518]
Please add support for the new AWS CodeArtifact service, detailed here:

https://aws.amazon.com/blogs/aws/software-package-management-with-aws-codeartifact/

Documentation:
https://docs.aws.amazon.com/codeartifact/latest/APIReference/Welcome.html
Category: Developer Tools 
Additional Context: This service was just released.

**Comment by richardhboyd** [comment]
Thanks @fimbulvetr! We are working on these resources and would love to get your feedback on how you’d like to manage CodeArtifact resources in CloudFormation.

**Comment by bisoldi** [comment]
For private packages, it should definitely allow the “insertion” of the package into CodeArtifact directly from the command line, similar to how we can upload a Lambda directly from the command line.  But I can also see value in that same insertion being done with a URL pointing to the original package in the public repository.  

Finally, it seems that many users often see value in having multiple CloudFormation”types”.  So, instead of providing the package details inline with the declaration of the CodeArtifact repository, have it broken out as a separate object so that we can n-number of packages.

**Comment by fimbulvetr** [comment]
@richardhboyd 
I think at the very least it would be nice to have AWS::CodeArtifact:Domain where we can optionally spec the encryption key and policy. This domain ideally would have a getatt/ref of both the ARN and name. 

Also AWS::CodeArtifact::Repository that accepts the domain arn as an argument as well as upstreams, policies, description and external connections. There should be getatt/refs of the arn, name and endpoint. 

This way we can have, for instance, a domain that covers an entire account or even project that we setup via cf. Then projects that depend on those can simply import from that stack the url for the artifact store. Projects might be something like codebuild that need to build an npm module and publish to that repository.

**Comment by HubbleDK** [comment]
Since "CodeArtifact uses Amazon Simple Storage Service (Amazon S3) to store package assets", what about specifying the S3 bucket directly in our template ? At Repository level ?

Is it also possible to think about a backup solution ?

**Comment by richardhboyd** [comment]
@HubbleDK we use S3 as the underlying storage mechanism but we don't expose the actual bucket to customers so there wouldn't be a need for customers to describe the bucket in their template.

What are you thinking for backup solutions ?

**Comment by HubbleDK** [comment]
I'm thinking about disaster recovery, imagine we cannot reach CodeArtifact, lost the entire VPC or worst, how can I get all my assets back asap ?

**Comment by richardhboyd** [comment]
CodeArtifact assets don't live in the VPC so losing the VPC wouldn't affect the assets. I suspect that re-establishing connectivity to CodeArtifact would be part of your broader DR process and not something specific to CodeArtifact. CodeArtifact relies on S3's 99.999999999% durability guarantee to ensure assets aren't lost but it sounds like you're looking for a cross-region replication feature to ensure availability in the unlikely event of a region-wide outage.

**Comment by HubbleDK** [comment]
> CodeArtifact assets don't live in the VPC so losing the VPC wouldn't affect the assets. I suspect that re-establishing connectivity to CodeArtifact would be part of your broader DR process and not something specific to CodeArtifact. CodeArtifact relies on S3's 99.999999999% durability guarantee to ensure assets aren't lost but it sounds like you're looking for a cross-region replication feature to ensure availability in the unlikely event of a region-wide outage.

Hmm, I think so, yes.

**Comment by melzareix** [comment]
Is there any estimate or progress on this? My team would like to use the service but not having it in cloudformation is blocking us

**Comment by PatMyron** [comment]
https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-codeartifact/

**Comment by richardhboyd** [comment]
@PatMyron can we move this issue to that Repo?
