### ISSUE TITLE
AWS::Athena::NamedQuery WorkGroup

### ISSUE THREAD

**Issue by rcolombo** [aws-cloudformation/aws-cloudformation-coverage-roadmap#525]
Please make WorkGroup a valid parameter for the AWS::Athena::NamedQuery resource.

Expected Behavior:
On create, the NamedQuery should be saved to the WorkGroup specified. If no WorkGroup is specified, it should be saved to the "primary" WorkGroup (this is the current behavior).

NamedQuery docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-athena-namedquery.html

This functionality is already supported by the AWS API - https://docs.aws.amazon.com/athena/latest/APIReference/API_CreateNamedQuery.html

**Comment by rohits-spec** [comment]
This property is supported https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-athena-namedquery.html#cfn-athena-namedquery-workgroup . Please note, CloudFormation resource will take primary workgroup unless you specify a different one, in the workgroup property.
