### ISSUE TITLE
AWS::DMS::Endpoint-Password-Add dynamic reference support

### ISSUE THREAD

**Issue by yiantony** [aws-cloudformation/aws-cloudformation-coverage-roadmap#534]
1. Title:
AWS::DMS::Endpoint-Password-Add dynamic reference support
2. Scope of request:
All below password support dynamic reference for secure strings, but not supported in AWS::DMS::Endpoint-Password
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#dynamic-references-ssm-secure-strings
AWS::DirectoryService::MicrosoftAD-Password
AWS::DirectoryService::SimpleAD-Password
AWS::ElastiCache::ReplicationGroup-AuthToken
AWS::IAM::User-Password
AWS::KinesisFirehose::DeliveryStream-Password
AWS::OpsWorks::App-Password
AWS::OpsWorks::Stack-Password
AWS::OpsWorks::Stack-DbPassword
AWS::RDS::DBCluster-MasterUserPassword
AWS::RDS::DBInstance-MasterUserPassword
AWS::Redshift::Cluster-MasterUserPassword

3. Expected behavior:
When creating AWS::DMS::Endpoint, we can use dynamic reference for the password.
Not supporting the dynamic reference has led to either
E1027: Dynamic References Secure Strings are only supported for a small set of resource properties. Validate that they are being used in the correct location when checking values and Fn::Sub in resource properties. Currently doesn't check outputs, maps, conditions, parameters, and descriptions.
or
W2501: Password properties should not be strings and if parameter using NoEcho
https://github.com/aws-cloudformation/cfn-python-lint/blob/master/docs/rules.md

4. Category tag -> Migration & Transfer
5. Any additional context:
Same issue was raised here for CDK but I was told that this is a CloudFormation request. https://github.com/aws/aws-cdk/issues/8349

**Comment by PatMyron** [comment]
generalizing and merging this into https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/227

`secretsmanager` [dynamic references](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html) are not limited to a hand maintained list of approved property types, so I see no reason why `ssm-secure`[dynamic references](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html) should be
