### ISSUE TITLE
AWS::EC2::PrefixList

### ISSUE THREAD

**Issue by irgeek** [aws-cloudformation/aws-cloudformation-coverage-roadmap#541]
[Managed PrefixLists](https://docs.aws.amazon.com/vpc/latest/userguide/managed-prefix-lists.html) were just announced, and they look to be pretty useful. It'd be great if we could create them from CloudFormation. I did a bit of searching and Google's cache has references (so maybe it's already in the pipeline) but I don't see it on the roadmap.

**Comment by fortunecookiezen** [comment]
We're an Fortune 500 FI, and this feature would be very useful for us to simplify the creation of hybrid network routes in route tables for subnets and transit gateways.

**Comment by networkpadawan** [comment]
Same here, this feature would be very helpful for our hybrid deployments

**Comment by JosePoscente** [comment]
+1 :)

**Comment by tqueiros** [comment]
1+

**Comment by cmelou** [comment]
+1

**Comment by saloni1009** [comment]
+1

**Comment by seittema** [comment]
I believe they actually already released this:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-prefixlist.html

According to the [cloudformation release history ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html)it came out July 9th

**Comment by luiseduardocolon** [comment]
Released Jul 9
