### ISSUE TITLE
AWS::Glue::Database-Support import operations

### ISSUE THREAD

**Issue by mgmarino** [aws-cloudformation/aws-cloudformation-coverage-roadmap#551]
## 2. Scope of request 

AWS::Glue::Database currently is not [listed as one of the public resources that supports import operations](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html).

This request is to enable import operations for this resource, which would allow e.g. transferring this resource between stacks.

## 3. Expected behavior

Import operations for AWS::Glue::Database should be supported.  This resource should be able to be transferred between stacks.

## 4. Suggest specific test cases

- Create Database in one stack, then migrate to new stack.

## 5. Helpful Links to speed up research and evaluation

Current resources supporting import operations: [link](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html)

## 6. Category

- Analytics

**Comment by PatMyron** [comment]
more generally tracking in https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/276
