### ISSUE TITLE
AWS::RDS::DBCluster-CopyTagsToSnapshot

### ISSUE THREAD

**Issue by abatkin** [aws-cloudformation/aws-cloudformation-coverage-roadmap#555]
`AWS::RDS::DBCluster` should support the "`CopyTagsToSnapshot`" field for Aurora database clusters.

This parameter is supported at the API-level (`CreateDBInstance` and `ModifyDBInstance`) but not CloudFormation.

The documentation for these API parameters are here:
* https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBCluster.html
* https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBCluster.html
Note that it *should* be possible to update this value on an existing cluster without replacing it.

**Comment by isobit** [comment]
Duplicate of #238, although there hasn't been an update on that in a while.

**Comment by abatkin** [comment]
Thanks @isobit I'll close this one, not sure how I missed that
