### ISSUE TITLE
AWS::CloudFormation::CustomResource - Support drift detection

### ISSUE THREAD

**Issue by pgarbe** [aws-cloudformation/aws-cloudformation-coverage-roadmap#557]
## 1. Title
AWS::CloudFormation::CustomResource - support drift detection

## 2. Scope of request 
Allow custom resources to detect drifts. 

## 3. Expected behavior
If implemented, also custom resource can be called to detect their drift and the results are reported back to the CloudFormation stack.

## 5. Helpful Links to speed up research and evaluation
Drift detection support in CloudFormation: 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-drift.html

## 6. Category

Other

**Comment by rjlohan** [comment]
As we have now launched the [Resource Provider](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-develop.html) and Registry Service framework which will support this feature (and others such as Resource Import) for non-AWS resource types, it's highly unlikely we would try to make the same features work for custom resource. 

These features benefit from some of the things we added with this capability that are not present in custom resources. The Drift Detection feature for example depends on a Read/Describe implementation which custom resources do not need to implement (and so none will have done so), schema to describe the shape of the resource in such a way that diff'ing can be performed on template and live resource state. 

I appreciate it's not necessarily a simple exercise to convert existing custom resources to this framework, but likewise it won't be a trivial exercise to retrofit these requirements into that framework for either the service, or customers.

**Comment by luiseduardocolon** [comment]
Closing since we won't pursue this.  We will support drift and import with the new resource providers, as stated above.  I'm also working with others in better samples and blogs on the process. Reach out if you would like to discuss migrating a specific custom resource.

**Comment by pgarbe** [comment]
Thanks for your honest feedback. I understand that Resource Provider are the better way but there are still some missing features that prevents me from using them.

**Comment by rjlohan** [comment]
Understood, if you have a laundry list of those, shoot them my way. I've seen some, but might have missed a couple. :)
