### ISSUE TITLE
AWS::CloudFront::Distribution should allow distributions to be imported into a new or existing stack

### ISSUE THREAD

**Issue by rshayman** [aws-cloudformation/aws-cloudformation-coverage-roadmap#559]
##  Scope of request 
Once in use, it not easy to migrate a CNAME from a CloudFront created outside of CloudFormation to one created by CloudFormation without potentially causing an outage.

## Expected behavior
An existing CloudFormation distribution can be imported into a new or existing CloudFormation stack.

## Category (required)
Networking & Content Delivery

**Comment by ikben** [comment]
There is a way to work around this, that is still a bit of a hassle but might solve your problem in the short term.

1. Create the Distribution with CFN, without the ALIAS configured
2. Follow the steps here: https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/ (creating a support case to move the ALIAS)
3. Update the stack to add the ALIAS to the distribution (bringing CloudFormation In sync with the actual state)

**Comment by PatMyron** [comment]
more generally tracking in https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/276

As [CloudFormation Registry](https://aws.amazon.com/blogs/aws/cloudformation-update-cli-third-party-resource-support-registry/) types [now automatically support resource import operations](https://aws.amazon.com/about-aws/whats-new/2020/06/aws-cloudformation-resource-import-supports-cloudformation-registry-types/), a [migration of this type to the newer Registry framework](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cloudfront/tree/master/aws-cloudfront-distribution) should pick this up automatically
