### ISSUE TITLE
AWS::CodeDeploy::DeploymentGroup-EcsServices

### ISSUE THREAD

**Issue by roberth-k** [aws-cloudformation/aws-cloudformation-coverage-roadmap#56]
## Scope of request 

The AWS::CodeDeploy::DeploymentGroup resource is currently missing `EcsServices`, which would be required for linking a deployment group to ECS. It is therefore not possible to use CodeDeploy with ECS if the deployment group has been provisioned with CloudFormation, despite the support in AWS::CodeDeploy::Application.

## Helpful Links to speed up research and evaluation

- [CodeDeploy API field reference](https://docs.aws.amazon.com/codedeploy/latest/APIReference/API_CreateDeploymentGroup.html#CodeDeploy-CreateDeploymentGroup-request-ecsServices)

## Category

1. Compute (EC2, ECS, EKS, Lambda...)
10. Developer Tools (CodeStar, ...)

**Comment by luiseduardocolon** [comment]
We're closing this issue - the functionality for this is expected to be handled when issue #130 is completed.

**Comment by joedj** [comment]
@luiseduardocolon Issue #130 is _AWS::CertificateManager::Certificate (Resource timeout)_ - is that what you meant?

**Comment by sisley900** [comment]
Yep

**Comment by luiseduardocolon** [comment]
Yes

**Comment by clareliguori** [comment]
@luiseduardocolon Can you re-open this issue please?  The `AWS::CodeDeploy::DeploymentGroup` resource type still has a coverage gap for the `EcsServices` attribute, which isn't covered by aws/containers-roadmap#130.  That issue covers the new CodeDeploy 'Hooks' template section, but not the existing CodeDeploy resource types. Thanks!

**Comment by smee30** [comment]
Would be awesome to get this fixed. It's the one thing standing in the way of us being able to use CF for end-to-end management of our environment.
