### ISSUE TITLE
AWS::CertificateManager::Certificate should allow to be imported into a new stack

### ISSUE THREAD

**Issue by OlafConijn** [aws-cloudformation/aws-cloudformation-coverage-roadmap#561]
Quick Sample Summary:

> I would expect resources of type `AWS::CertificateManager::Certificate ` to be importable using CloudFormation 

Category (required) - Will help with tagging and be easier to find by other users to +1

> Security (IAM, KMS...)

**Comment by PatMyron** [comment]
more generally tracking in https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/276

As [CloudFormation Registry](https://aws.amazon.com/blogs/aws/cloudformation-update-cli-third-party-resource-support-registry/) types [now automatically support resource import operations](https://aws.amazon.com/about-aws/whats-new/2020/06/aws-cloudformation-resource-import-supports-cloudformation-registry-types/), a [migration of this type to the newer Registry framework](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-certificatemanager/tree/master/aws-certificatemanager-certificate) should pick this up automatically
