### ISSUE TITLE
AWS::CodeGuruReviewer::RepositoryAssociation

### ISSUE THREAD

**Issue by luiseduardocolon** [aws-cloudformation/aws-cloudformation-coverage-roadmap#569]
AWS::CodeGuruReviewer::RepositoryAssociation

2. Scope of request -> AWS::CodeGuruReviewer::RepositoryAssociation
3. Expected behavior -> support repo association in CFN create, update, and delete operations
4. Test case recommendation (optional) -> open to specific use case scenarios, feel free to ask questions in this thread.
5. Links to existing API doc (optional) -> 
6. Category tag (optional) -> DevTools

**Comment by PatMyron** [comment]
[`AWS::CodeGuruReviewer::RepositoryAssociation`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codegurureviewer-repositoryassociation.html)

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html
