### ISSUE TITLE
CloudFormation in region eu-central-1 does not recognize AWS::SES::Template despite SES is available

### ISSUE THREAD

**Issue by kirnberger1980** [aws-cloudformation/aws-cloudformation-coverage-roadmap#579]
According to the following thread is SES available in eu-central-1, but CF in eu-central-1 does not recognize **AWS::SES::Template**

https://forums.aws.amazon.com/thread.jspa?threadID=316103

When I try to create a stack with this resource type I get the following error:
```
An error occurred (ValidationError) when calling the CreateStack operation: Template format error: Unrecognized resource types: [AWS::SES::Template]
```

So there could be some problem with CF in this region!?

**Comment by PatMyron** [comment]
tracking in https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/326
