### ISSUE TITLE
AWS::Cognito::UserPool-LambdaConfig (new properties)

### ISSUE THREAD

**Issue by patrickgreenwell** [aws-cloudformation/aws-cloudformation-coverage-roadmap#59]
## Scope of Request
AWS::Cognito::UserPool-LambdaConfig attribute curently supports Lambda Triggers in cloud formation  for : 
* `CreateAuthChallenge`
* `CustomMessage`
* `DefineAuthChallenge`
* `PostAuthentication`
* `PostConfirmation`
* `PreAuthentication`
* `PreSignUp`
* `VerifyAuthChallengeResponse` 

It does not support `PreTokenGeneration` and `UserMigration` these attributes should be added to allow the same support that the API allows for in the [UpdateUserPool](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserPool.html) and [CreateUserPool ](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateUserPool.html)API Calls

#### Pass them in a similar manner as the other Lambda Configs
Type: String
Minimum: 20
Maximum: 2048
Pattern: arn:[\w+=/,.@-]+:[\w+=/,.@-]+:([\w+=/,.@-]*)?:[0-9]+:[\w+=/,.@-]+(:[\w+=/,.@-]+)?(:[\w+=/,.@-]+)?
Update requires: No interruption

## 5. Helpful Links to speed up research and evaluation
Cloud Formation API Documentation : [AWS::Cognito::UserPool-LambdaConfig](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-lambdaconfig.html)
Cognito User Pool API docs
[UpdateUserPool](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserPool.html) 
[CreateUserPool ](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateUserPool.html)

## 6. Category 
Security, Identity, & Compliance

**Comment by dan-lind** [comment]
I was suprised to find that it looks like this is already supported?

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-lambdaconfig.html

I actually created a custom resource for this specific use case about a year ago. 
The weird thing is that if I look through the release notes there is no mention of this ever being added: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html#release-history-earlier-updates

**Comment by luiseduardocolon** [comment]
@dan-lind check the latest release of Cognito update to verify this too.  Let me know if we should move this to shipped and close the issue.
