### ISSUE TITLE
AWS::CodeBuild::Project BatchBuildConfig

### ISSUE THREAD

**Issue by shekharsh75** [aws-cloudformation/aws-cloudformation-coverage-roadmap#590]
1. Title

AWS::CodeBuild::Project does not have support for BatchBuildConfig
2. Scope of request

CloudFormation support for BatchBuildConfig
3. Expected behavior

Ability to use Code Build batch builds with CloudFormation.
5. Helpful Links to speed up research and evaluation

https://aws.amazon.com/about-aws/whats-new/2020/07/aws-codebuild-now-supports-parallel-and-coordinated-executions-of-a-build-project/
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html

6. Category (required) - Will help with tagging and be easier to find by other users to +1

Developer Tools (Codebuild, ...)

**Comment by PatMyron** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html#cfn-codebuild-project-buildbatchconfig
