### ISSUE TITLE
AWS::Athena::NamedQuery WorkGroup property

### ISSUE THREAD

**Issue by MGaber86** [aws-cloudformation/aws-cloudformation-coverage-roadmap#596]
## Instructions for CloudFormation Coverage New Issues Template

Quick Sample Summary:
1. Title -> AWS::Athena::NamedQuery WorkGroupId
2. Scope of request -> AWS::Athena::NamedQuery to support attaching WorkGroup (Check AWS SDK: https://docs.aws.amazon.com/athena/latest/APIReference/API_CreateNamedQuery.html) 
3. Expected behavior -> When Create NamedQuery, I should be able to attach the query to sepcific Athena Workgroup. Currently, NamedQuery goes to primary WorkGroup
4. Test case recommendation (optional) -> it should help me do X given existing Y (if applicable); it should/shouldn't change Z.
5. Links to existing API doc (optional) -> https://docs.aws.amazon.com/athena/latest/APIReference/API_CreateNamedQuery.html
6. Category tag (optional) -> DB
7. Any additional context (optional) N/A

**Comment by rohits-spec** [comment]
This property is supported https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-athena-namedquery.html#cfn-athena-namedquery-workgroup . Please note, CloudFormation resource will take primary workgroup unless you specify a different one, in the workgroup property.
