### ISSUE TITLE
AWS::IAM::Role (allow adding a Description)

### ISSUE THREAD

**Issue by luiseduardocolon** [aws-cloudformation/aws-cloudformation-coverage-roadmap#6]
Quick Sample Summary:
1. Title -> AWS::AWS::IAM::Role does not expose the ability to add a Description to the role, which is supported in the CreateRole API.
2. Scope of request -> Allow the ability to add a description to a role when creating it.  Also need to add descriptions to previously related roles. 
3. Expected behavior -> Match the CreateRole API as it relates to descriptions.  Also, changing descriptions to existing roles is available via the console. 
4. Test case recommendation (optional) -> Cover the 2 cases above (see 3).
5. Links to existing API doc (optional) -> https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateRole.html
6. Category tag (optional) -> Security
7. Any additional context (optional)

**Comment by stan1y** [comment]
How about "Tags" support as well?

**Comment by pbsinclair42** [comment]
Looks like this is now supported; https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-description
