### ISSUE TITLE
AWS::WAF::RateBasedRule

### ISSUE THREAD

**Issue by rclark** [aws-cloudformation/aws-cloudformation-coverage-roadmap#60]
## 2. Scope of request 

Implement a new resource type to provision a [WAF RateBasedRule](https://docs.aws.amazon.com/waf/latest/APIReference/API_RateBasedRule.html?shortFooter=true). 

Note this has been implemented for WAF Regional, but not for WAF (global).

## 6. Category 

Security, Identity, and Compliance

**Comment by mibollma** [comment]
For *WAF Regional* it [doesn't seem to work as expected](https://stackoverflow.com/questions/56683755/sam-api-gateway-with-cloudformation-wafregional/) either.

Creating the rule works, associating it with a *WebACL* doesn't.

**Comment by jamiepmullan** [comment]
> For _WAF Regional_ it [doesn't seem to work as expected](https://stackoverflow.com/questions/56683755/sam-api-gateway-with-cloudformation-wafregional/) either.
> 
> Creating the rule works, associating it with a _WebACL_ doesn't.

Would be great if you could associate it from the template, nasty work arounds need to be in place while this doesn't work.

**Comment by brianterry** [comment]
Hello!
This resource property is now supported by AWS CloudFormation.

Please see our docs for more details:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-rulegroup-ratebasedstatement.html
