### ISSUE TITLE
AWS::RDS::OptionGroup & AWS::RDS::DBParameterGroup have no way to pass in a Name 

### ISSUE THREAD

**Issue by kenerwin88** [aws-cloudformation/aws-cloudformation-coverage-roadmap#618]
## 1. Quick Summary
It is currently not possible to pass in a name when creating an RDS OptionGroup or DB Parameter Group (AWS::RDS::OptionGroup & AWS::RDS::DBParameterGroup).  We should be able to pass in an "OptionGroupName", and "DBParameterGroupName" respectively.

## 2. Scope of request 
New attribute for two existing resources.  Need "OptionGroupName" added to AWS::RDS::OptionGroup, and "DBParameterGroupName" to AWS::RDS:DBParameterGroup.

## 3. Expected behavior
We should be able to pass in a name when creating an OptionGroup or DBParameterGroup, but currently you are forced to have a generated name unless you create them manually (outside of Cloudformation).

## 4. Suggest specific test cases
Try to create an OptionGroup or DBParameterGroup with a specific name using Cloudformation, you won't be able to.

## 5. Helpful Links to speed up research and evaluation
This will also need to be added to AWS CDK after this is fixed.  
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-optiongroup.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-dbparametergroup.html
Similar Issue someone else posted for Elasticache https://github.com/aws/aws-cdk/issues/8180

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1
DB (RDS)

**Comment by PatMyron** [comment]
merging into previously opened https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/212 for one of these and expanding to include both
