### ISSUE TITLE
AWS::Cloudformation::Stack - Pseudo Parameters

### ISSUE THREAD

**Issue by brain-is-afk** [aws-cloudformation/aws-cloudformation-coverage-roadmap#642]
## Instructions for CloudFormation Coverage New Issues Template

Quick Sample Summary:
possible :) ). 

## 1. Title 

AWS::Cloudformation::Stack - Parameters

## 2. Scope of request 
Add additional Pseudo Parameters for organization resources such as OU.  For organization deployed stacks, using these parameters can conditionally build resources for given units specific to how an organization defines them.  Examples would be implementing a Production IAM Policy for a role vs a Development IAM Policy.  

## 3. Expected behavior

Condition:
   Fn:Equals
        - AWS::OU
        - ou-a1b23

This would check OU membership ( potentially recursively ) to be able to toggle resources in stacks.  Especially useful when deploying in stack sets and organizations.

## 4. Suggest specific test cases

Run stack with above condition type

## 5. Helpful Links to speed up research and evaluation

no known links

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Use the categories as displayed in the AWS Management Console (simplified):

5. Management (CloudTrail, Config...)

**Comment by PatMyron** [comment]
Going to add this to https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/160, both should be implemented together
