### ISSUE TITLE
AWS::CloudFront::Distribution-OriginGroups

### ISSUE THREAD

**Issue by ericlackey** [aws-cloudformation/aws-cloudformation-coverage-roadmap#65]
## Scope of Request

New attribute for an existing resource is desired 

AWS::CloudFront::Distribution - Add support for using Origin Groups in CloudFront distributions. 

## Expected Behavior

You should be able to specify an OriginGroups attribute that allows for one or more OriginGroups where each OriginGroup references multiple Origin IDs on the distribution. It will need to support OriginGroup failover criteria and the ability to provide an ID for the OriginGroup.

You should then be able to map behavior rules to either an Origin or an OriginGroup.
    
## Links to existing API doc

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-distribution.html

## Category Tag

Networking

**Comment by mpriestel** [comment]
We're are kind of stuck with deploying production infrastructure because of this feature not existing in cloudformation. We would like to have this feature ASAP, since all of our infrastructure is written in cloudformation which is the official AWS IaaC tool.

**Comment by jverneuer** [comment]
is there an estimate when this will be available. 
It's quite a critical feature for us. 
Account id's:
363191405432
454597441955
103057822433
274055544780
819922370039
790761275960
508482343126
266383369026
883480099551
555859027902

**Comment by ngamradt-turner** [comment]
Is there an update as to when this feature will roll out?

**Comment by rjlohan** [comment]
> is there an estimate when this will be available.
> It's quite a critical feature for us.

@jverneuer I updated your comment here to remove Account IDs. Whilst not a major concern, it's a small part of your AWS Identity and you should avoid sharing it online like this. Also, coverage support is applied globally to all customers and account IDs are not used to whitelist customers for access.

**Comment by kennu** [comment]
I'm also waiting for this, in order to use AWS CDK to define CloudFront Origin Groups. https://github.com/aws/aws-cdk/issues/3295

**Comment by mohdemraan** [comment]
When it will be released? Please give some estimate.

**Comment by luiseduardocolon** [comment]
The reason is hasn't been deployed is that a couple of issues have been found late in the process, but it appears that they will be resolved soon.  We are looking to release in the next 4 weeks or sooner.

**Comment by luiseduardocolon** [comment]
The deployment of this was finished earlier today :)

**Comment by tomgidden** [comment]
Is this deployed in `eu-west-2` at this time?  I'm still getting `[Encountered unsupported properties in {/DistributionConfig}: [OriginGroups]]`
