### ISSUE TITLE
AWS::ECR::Repository-EncryptionConfiguration

### ISSUE THREAD

**Issue by hommada** [aws-cloudformation/aws-cloudformation-coverage-roadmap#654]
As of Jul 29, 2020 ECR now supports encryption of images using AWS KMS keys.
https://aws.amazon.com/about-aws/whats-new/2020/07/ecr-supports-encryption-images-aws-kms-keys/

Please add EncryptionConfiguration property to AWS::ECR::Repository resource type.

AWS::ECR::Repository
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html

EncryptionConfiguration
https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_EncryptionConfiguration.html

**Comment by bradgr** [comment]
Thank you for raising this. Getting this added is now under consideration. Please follow aws-cloudformation/aws-cloudformation-resource-providers-ecr#15 for further tracking.

**Comment by kddejong** [comment]
This has been implemented

https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ecr/issues/15#issuecomment-837394888
