### ISSUE TITLE
AWS::AutoScaling::AutoScalingGroup-CapacityRebalance

### ISSUE THREAD

**Issue by Trane9991** [aws-cloudformation/aws-cloudformation-coverage-roadmap#673]
## Scope of request 
`AWS::AutoScaling::AutoScalingGroup` doesn't support the newly introduced `CapacityRebalance`

## Helpful Links to speed up research and evaluation

[Introducing EC2 Instance rebalance recommendation for EC2 Spot Instances](https://aws.amazon.com/about-aws/whats-new/2020/11/introducing-ec2-instance-rebalance-recommendation-for-ec2-spot-instances/)
[Amazon EC2 Auto Scaling Capacity Rebalancing](https://docs.aws.amazon.com/autoscaling/ec2/userguide/capacity-rebalance.html)

## Category

Compute (ASG)

**Comment by iann0036** [comment]
Does now :)

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

**Comment by Trane9991** [comment]
Indeed, thanks!
