### ISSUE TITLE
CFN Cost estimate does not work for AWS::EMR::Cluster resource

### ISSUE THREAD

**Issue by aloknew** [aws-cloudformation/aws-cloudformation-coverage-roadmap#675]
I am trying to estimate my CFN template cost which contains AWS::EMR::Cluster resource.

However cost estimator says 0.0$ as estimate which is wrong.

Can you please suggest

**Comment by PatMyron** [comment]
only a few services are currently supported. more generally tracking in https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/217 so I'll merge this issue into that one
