### ISSUE TITLE
AWS::SNS::Topic (allow tags)

### ISSUE THREAD

**Issue by luiseduardocolon** [aws-cloudformation/aws-cloudformation-coverage-roadmap#7]
1. Title -> SNS supports tagging and untagging topics, and it should be supported in CloudFormation.
2. Scope of request -> Allow for tags on create, updating tags, etc.
3. Expected behavior -> See 2 above. 
4. Test case recommendation (optional) -> 
5. Links to existing API doc (optional) -> 
6. Category tag (optional) -> App Integration
7. Any additional context (optional)

This was announced: https://aws.amazon.com/about-aws/whats-new/2019/05/amazon-sns-adds-support-for-cost-allocation-tags/

**Comment by JensWalter** [comment]
It would be helpful if tag support would also cover the aws cloudformation tags.

- aws:cloudformation:stack-id
- aws:cloudformation:stack-name
- aws:cloudformation:logical-id

**Comment by LaikaN57** [comment]
It looks like SNS Topics now support custom tags, however it would be really useful to auto add the aws:* tags. Do you want another ticket for that or are we tracking that here?

**Comment by tstibbs** [comment]
I've raised #652 for the issue that the `aws:cloudformation:*` tags aren't propagated.
