### ISSUE TITLE
AWS::DynamoDB::Table-KinsesisDataStream

### ISSUE THREAD

**Issue by robertkross** [aws-cloudformation/aws-cloudformation-coverage-roadmap#707]
1. Title -> AWS::DynamoDB::Table-KinsesisDataStream
2. Scope of request -> AWS::DynamoDB::Table-KinsesisDataStream to enable to create the new Kinsesis Data Stream integration with DynamoDB also with cloudformation and not only via console / CLI.
3. Expected behavior ->In Create, the table should be created + the data stream should be created implicitly.
6. Category tag -> DB

**Comment by mailjunze** [comment]
Any update on how soon ?

**Comment by rohits-spec** [comment]
The support was added as part of KinesisStreamSpecification property as documented here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-kinesisstreamspecification.

**Comment by ankon** [comment]
This is great news, and I wanted to quickly move our [custom-resource based approach](https://medium.com/collaborne-engineering/enable-dynamodb-to-kinesis-streaming-with-cloudformation-f26180c6923) to using this instead. But, the configuration seems to require that the DynamoDB table doesn't have the kinesis data stream enabled already. Obviously I cannot just disable the stream, as that would mean I lose the change data in that period.

The error I'm hitting is:
```
Table is not in a valid state to enable Kinesis Streaming Destination: EnableKinesisStreamingDestination must be DISABLED or ENABLE_FAILED to perform ENABLE operation. (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: ...; Proxy: null)
```

It would be desirable that a update (representing the intent "should be active") would be a no-op when the streaming is already configured and currently active.

**Comment by benbridts** [comment]
@ankon That's fairly normal behaviour, as for CloudFormation (looking only at the previous template), the Destination wasn't configured yet.

You can however work around that error, by:

1.  Adding a DeletionPolicy to your table resource and updating the stack with this
1. Removing the Table from the template / stack
1. [Re-importing the table with the existing configuration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-existing-stack.html).

**Comment by ankon** [comment]
@benbridts thanks -- I'll try that over the coming days. Unfortunately this affects not just one, but about a hundred tables right now, distributed over multiple AWS accounts and stacks. As such I end up having to work out some pretty fail-safe automatic approach. Not a "impossible!", but definitely "interesting!" :)
