### ISSUE TITLE
AWS::DynamoDB::Table-ContributorInsights

### ISSUE THREAD

**Issue by cmckni3** [aws-cloudformation/aws-cloudformation-coverage-roadmap#708]
## Scope of request 

   c) new attribute for an existing resource is desired 

ContributorInsights is not available in CFN for AWS::DynamoDB::Table.

Should be able specify a template property on the DynamoDB table to enable contributor insights. Contributor Insights for DynamoDB will help identify hot partition and/sort keys in development and production.

## Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/contributorinsights_HowItWorks.html

## Category (required) - Will help with tagging and be easier to find by other users to +1

3. DB (RDS, DynamoDB...)

**Comment by rohits-spec** [comment]
Launched on 2/22.
