### ISSUE TITLE
AWS::EKS::Nodegroup-CapacityType

### ISSUE THREAD

**Issue by pahud** [aws-cloudformation/aws-cloudformation-coverage-roadmap#712]
## 2. Scope of request 

c) new attribute for an existing resource is desired 

#### AWS::EKS::Nodegroup-CapacityType to pass `CapacityType` to nodegroup API.

`capacityType` is mentioned in the document
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-nodegroup.html
But is actually not available for `AWS::EKS::Nodegroup`

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Use the categories as displayed in the AWS Management Console (simplified):

1. Compute (EKS)

**Comment by kirintwn** [comment]
Hi @pahud,
I do believe they have implemented this feature already, the paramater name is: `CapacityType`, possible values are `SPOT` & `ON_DEMAND` . Our team are already using this with CloudFormation. They haven't put it on any official documentation through.

**Comment by pahud** [comment]
@pahud really appreciated!
