### ISSUE TITLE
AWS::EC2::LaunchTemplate-LaunchTemplateData-BlockDeviceMappings-Ebs-Throughput

### ISSUE THREAD

**Issue by makotech-d** [aws-cloudformation/aws-cloudformation-coverage-roadmap#729]
## 1. Title 
AWS::EC2::LaunchTemplate-LaunchTemplateData-BlockDeviceMappings-Ebs-Throughput

## 2. Scope of request 
AWS::EC2::Volume now supports the `Throughput` parameter for `gp3`, but we cannot set the `Throughput` patameter in LaunchTemplate. CloudFormation needs support for this. 

## 3. Expected behavior

In Create, it should allow us to set the `Throughput` parameter on AWS::EC2::LaunchTemplate-LaunchTemplateData-BlockDeviceMappings-Ebs. 

## 4. Suggest specific test cases

Common use case: referencing `Throughput` from a stack parameter, and changing `Throughput` without any operating on AWS Management Console.

## 5. Helpful Links to speed up research and evaluation

AWS::LaunchTemplate-Ebs: https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html
AWS::EC2::Volume-Properties: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-ebs-volume.html#cfn-ec2-ebs-volume-throughput

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

1. Compute (EC2, ECS, EKS, Lambda...)
10. Developer Tools (CodeStar, ...)

**Comment by rshayman** [comment]
Seriously, how difficult is to add gp3 to a list of allows parameters.  It was announced 3 and half months ago.

**Comment by rohits-spec** [comment]
This is currently supported. Following is the doc link on the same. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html#cfn-ec2-launchtemplate-blockdevicemapping-ebs-volumetype 

Marking this as shipped. Please reopen if the ask isnt addressed.
