### ISSUE TITLE
AWS::Glue::Trigger-Enabled (new property)

### ISSUE THREAD

**Issue by pbsinclair42** [aws-cloudformation/aws-cloudformation-coverage-roadmap#73]
1. Scope of request -> New attribute for an existing resource.  AWS::Glue::Trigger should include an option to enable/disable SCHEDULED and CONDITIONAL triggers
2. Expected behavior -> If the Trigger is of type SCHEDULED or CONDITIONAL: In Create, it should set the StartOnCreation flag to the value of this field so that once the trigger is created it will automatically be enabled/disabled as appropriate.  In Update, it should enable/disable the trigger based on the value of this flag, without requiring replacement.  If the Trigger is of type ON_DEMAND: the value of this field should be ignored.
3. Links to existing API doc -> API docs: https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-jobs-trigger.html , developer's docs: https://docs.aws.amazon.com/glue/latest/dg/trigger-job.html
4. Category tag -> Analytics

**Comment by straygar** [comment]
Specifically - setting the `StartOnCreation` flag is what should be exposed.

**Comment by pbsinclair42** [comment]
Fantastic, looks like this is now supported, thanks! https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-trigger.html#cfn-glue-trigger-startoncreation
