### ISSUE TITLE
[ECR]: Add CloudFormation Support for Assigning KMS Keys to Repository

### ISSUE THREAD

**Issue by ngamradt-turner** [aws-cloudformation/aws-cloudformation-coverage-roadmap#771]
AWS ECR supports assigning a custom KMS key for encryption instead of just using the default AES-256 encryption:

https://aws.amazon.com/about-aws/whats-new/2020/07/ecr-supports-encryption-images-aws-kms-keys/

We need an attribute added to the "AWS::ECR::Repository" CloudFormation resource which will allow a KMS key to be assigned.  In most cases, this attribute is generally named "KmsKeyId".

Once this work is completed, I would expect to be able to assign a KMS key to my ECR repository via CloudFormation.

**Comment by pplu** [comment]
Any plans on getting this added? The support for KMS in ECR has been available since July 2020. At least we are using custom keys on lots of resources (everything done in CloudFormation), and ECR stands out for not having the KMS key property :(

**Comment by s1rl3o** [comment]
Would be grate to get any update on this.
Currently we are using the workaround to create the repositories manually with a KMS key.
Afterwards we import them to a corresponding CloudFormation stack.
Not nice, but effective!

**Comment by bradgr** [comment]
Thank you for raising this. Getting this added is now under consideration. Please follow https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ecr/issues/15 for further tracking.

**Comment by neijurli** [comment]
The property is now supported: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#cfn-ecr-repository-encryptionconfiguration.

You can also find the specific details to the new property in the resource specifications [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html).
