### ISSUE TITLE
[ECR]: Add CloudFormation Support for Public Repository Creation

### ISSUE THREAD

**Issue by ngamradt-turner** [aws-cloudformation/aws-cloudformation-coverage-roadmap#772]
AWS ECR now supports public repositories:

https://aws.amazon.com/blogs/aws/amazon-ecr-public-a-new-public-container-registry/

I do not see an attribute in CloudFormation to distinguish between public and private repositories:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html

An attribute needs to be added to the "AWS::ECR::Repository" resource so that a public ECR can be created.  Currently it appears that only a private ECR can be created via CloudFormation.

Once this attribute is added, I would expect to be able to create a public ECR repository via CloudFormation.

**Comment by jk2l** [comment]
@ngamradt-turner I think it is different resource https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-publicrepository.html

**Comment by rohits-spec** [comment]
The same is available as this resource: 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-publicrepository.html
