### ISSUE TITLE
AWS::EKS::Nodegroup-ExistingAttribute-Tags

### ISSUE THREAD

**Issue by richardkeit** [aws-cloudformation/aws-cloudformation-coverage-roadmap#795]
#### AWS::EKS::Nodegroup-ExistingAttribute-Tags acts as metadata of Nodegroup but **does not propagate** to underlying EC2 resources (unlike `AWS::AutoScaling::AutoScalingGroup`)

> Node group tags do not propagate to any other resources associated with the node group, such as the Amazon EC2 instances or subnets.

## Expected behavior

Tags at Cloudformation Stack level and at `AWS::EKS::Nodegroup-ExistingAttribute-Tags` are merged and propogated onto EC2 resources (EC2 Instance + Security Group).
Alternate solution additional delineation (for backwards compatibility) :
~~~yaml
      Tags:
        - Key: this-is-meant-for-ec2
          PropagateAtLaunch: true
          Value: please-tag-me
~~~

## Suggest specific test cases

Samples:
## Category 

Use the categories as displayed in the AWS Management Console (simplified):

1. Compute (EC2, EKS)

**Comment by rtripat** [comment]
Tags from AWS::EKS::Nodegroup aren't applied to the ASG (or EC2 instances). see containers roadmap [issue](https://github.com/aws/containers-roadmap/issues/608). 

However, if are using a custom launch template with a Managed Nodegroup then you can apply tags to Ec2 instances (not the ASG). See documentation [here](https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html#launch-template-tagging).

**Comment by richardkeit** [comment]
> Tags from AWS::EKS::Nodegroup aren't applied to the ASG (or EC2 instances). see containers roadmap [issue](https://github.com/aws/containers-roadmap/issues/608). 
> 
> However, if are using a custom launch template with a Managed Nodegroup then you can apply tags to Ec2 instances (not the ASG). See documentation [here](https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html#launch-template-tagging).

Agree. When wanting apply this at scale with dynamic key/value pairs for tags (using the same cloudformation template), propagation from Stack level tags seems the most native / non-bespoke way of making it happen

**Comment by rohits-spec** [comment]
Based on rtripat's comment, am closing this issue.

**Comment by richardkeit** [comment]
@rohits-spec - did you read the testing on mentioned on this ticket?
Tag is populated at [AWS Cloudformation Stack level](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html#cfn-cloudformation-stack-tags) and it visible on EC2 node in NodeGroup

Tagging at the EC2 Launch template does **not** satisfy the requirement
