### ISSUE TITLE
AWS::ElasticSearch:Domain (support Zone Awareness)

### ISSUE THREAD

**Issue by luiseduardocolon** [aws-cloudformation/aws-cloudformation-coverage-roadmap#8]
1. Title -> Customers want to set ZoneAwarenessConfig in Elastic Search
2. Scope of request -> Add two configuration options: ZoneAwarenessConfig and ZoneAwarenessEnabled
3. Expected behavior -> See API docs.
4. Test case recommendation (optional) -> 
5. Links to existing API doc (optional) ->https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-configuration-api.html#es-configuration-api-datatypes-elasticsearchclusterconfig
6. Category tag (optional) -> Analytics
7. Any additional context (optional)

**Comment by natefox** [comment]
Would love to see `LogPublishingOptions` and `CognitoOptions` added as well!

**Comment by autarchprinceps** [comment]
Does this include the ability to deploy AWS ES in 3az or should that be opened in a different issue? Because that is broken as well.
