### ISSUE TITLE
Service Control Policy Support

### ISSUE THREAD

**Issue by jamelongamzn** [aws-cloudformation/aws-cloudformation-coverage-roadmap#806]
Scope of Request:  Requesting Cloudformation support for SCPs to make it easier to deploy service control policys (SCP).  As part of this release it would be important to be able to import existing SCPs into a Cloudformation stack

Expected Behavior:  
     Ability to describe a service control policy in a cloudformation template.  
     Ability to deploy SCPs to many accounts through Stacksets
     Ability to import existing SCPs into a Cloudformation stack.  Most customers will have many SCPs already created and would not want to delete them as they are an important security control for their AWS Organizations.

https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html

Categories:  Organizations, IAM

**Comment by PatMyron** [comment]
tracking in https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/34
