### ISSUE TITLE
[Cloudformation custom resource type] - passing api keys to read handler

### ISSUE THREAD

**Issue by 422158** [aws-cloudformation/aws-cloudformation-coverage-roadmap#810]
## 1. Title 
[Cloudformation custom resource type] - passing properties to read handler

## 2. Scope of request 
I have been implementing CF custom resource type in golang. And when I see custom resource type I do NOT mean lambda backed custom resource but this: https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-test-contract.html

The resource type is hosted at third party provider (Atlas Mongo). In order to perform operations on the third party provider I need **api keys** in my handler. I am **passing these api keys as a part of config (model).**
There is no problem with "create handler" as the "create handler" receives entire config (including api keys).

There is PROBLEM with "read handler" as **this handler only receives id of the resource,** because according to contract: "The input to a read handler MUST contain either the primaryIdentifier or an additionalIdentifier. Any other properties MAY NOT be included in the request.".

However I am unable to read the resource without Api keys. Am I doing something wrong or is there NO way to get other properties than "id" into read handler?

## 3. Expected behavior

Read handler should receive all of the config properties. Without this the whole concept of custom resource types seems unusable. I am not even able to read an attribute from created cloudformation resource (since this requires Read opeartion, which fails due to missing api keys). Surprisingly, delete handler has same contract as read handler (according to docs), but it does receive all properties. 

## 5. Helpful Links to speed up research and evaluation

Here is documentation for handler contracts: https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-test-contract.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

11. Other (IoT, Migration, Budgets...)

**Comment by PatMyron** [comment]
tracking in https://github.com/aws-cloudformation/cloudformation-cli/issues/630
