### ISSUE TITLE
EC2 imdsv2 support

### ISSUE THREAD

**Issue by networkpadawan** [aws-cloudformation/aws-cloudformation-coverage-roadmap#826]
support to AWS::EC2::Instance Metadata option should be added

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html

ec2:MetadataHttpTokens
ec2:MetadataHttpPutResponseHopLimit
ec2:MetadataHttpEndpoint 

parameters are missing

enabling a best practice to block imdsv1 breaks the deploy of instances done via cloudformation.

**Comment by benbridts** [comment]
Hi @networkpadawan,
 
This is the same request as #655, so it's probably best to add your vote to that issue (by pressing the 👍  button)

**Comment by networkpadawan** [comment]
thanks @benbridts  misssed it:) will do and close this one
