### ISSUE TITLE
AWS::CloudFormation::StackSet-RegionConcurrency

### ISSUE THREAD

**Issue by jfoy** [aws-cloudformation/aws-cloudformation-coverage-roadmap#836]
The CloudFormation API was recently updated to support deploying a StackSet concurrently across multiple regions, but the AWS::CloudFormation::StackSet resource does not support this feature.

The property should support SEQUENTIAL and PARALLEL values.

Category: Management

**Comment by rohits-spec** [comment]
We have shipped this feature. Please find details here: 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudformation-stackset-operationpreferences.html#cfn-cloudformation-stackset-operationpreferences-regionconcurrencytype

**Comment by jfoy** [comment]
Thank you!
