### ISSUE TITLE
AWS::Lambda::Function - ZipFile Support for NodeJS 14 

### ISSUE THREAD

**Issue by varun656** [aws-cloudformation/aws-cloudformation-coverage-roadmap#843]
## 1. Title 
[Feature Request] Cloudformation Lambda function support for NodeJS 14

## 2. Scope of request 
Looking into the Lambda function creation it now supports NodeJs 14.x however, within CloudFormations AWS::Lambda::Function resources logic this is not yet supported. So attempting to create a function with this configuration will always fail. The feature request is to add support to use “ZipFile” sub-property of the property “Code” for NodeJS 14

Error faced: "ZipFile can only be used when Runtime is set to either of nodejs8.10, nodejs10.x, nodejs12.x, python2.7, python3.6, python3.7, python3.8.”

## 3. Expected behavior
 “[ZipFile](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html#cfn-lambda-function-code-zipfile)” sub-property of the property “Code” for the resource “AWS::Lambda::Function” should allow support for NodeJs 14.

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

CloudFormation Template : AWS::Lambda::Function

**Comment by benbridts** [comment]
see also #80

**Comment by PatMyron** [comment]
tracking in #80
