### ISSUE TITLE
AWS::S3::AccessPointForObjectLambda (S3 Object Lambda)

### ISSUE THREAD

**Issue by jansepke** [aws-cloudformation/aws-cloudformation-coverage-roadmap#845]
## 1. Title 
AWS::S3::AccessPointForObjectLambda

## 2. Scope of request
add CloudFormation support for new AWS S3 Object Lambda using Object Lambda Access Points. I don't know if AWS::S3::AccessPointForObjectLambda is the best fitting name.

## 3. Expected behavior
Should support creating S3 Object Lambda Access Points as described here: https://docs.aws.amazon.com/AmazonS3/latest/userguide/olap-create.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Use the categories as displayed in the AWS Management Console (simplified):

1. Compute (Lambda)
2. Storage (S3)

**Comment by benbridts** [comment]
This exists as [AWS::S3ObjectLambda::AccessPoint](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3objectlambda-accesspoint.html), which makes it easy to miss.

**Comment by jansepke** [comment]
thank you, that is indeed hard to find.

will post it here https://github.com/aws/aws-cdk/issues/13675
