### ISSUE TITLE
AWS::Athena::WorkGroup (new resource)

### ISSUE THREAD

**Issue by pbsinclair42** [aws-cloudformation/aws-cloudformation-coverage-roadmap#90]
1. Scope of request -> New resource type for an existing service: it should be possible to create Athena WorkGroups via CloudFormation; it's currently only supported by the API
2. Expected behavior -> In Create, it should create a workgroup with the appropriate settings. In Update, it should update the existing workgroup with the appropriate settings without replacement for all attributes other than Name.  In Delete, it should recursively delete the workgroup and its contents even if the workgroup contains any named queries.
3. Links to existing API doc -> [Create WorkGroup API docs](https://docs.aws.amazon.com/athena/latest/APIReference/API_CreateWorkGroup.html), [UpdateWorkGroup API docs](https://docs.aws.amazon.com/athena/latest/APIReference/API_UpdateWorkGroup.html), [DeleteWorkGroup API docs](https://docs.aws.amazon.com/athena/latest/APIReference/API_DeleteWorkGroup.html), [Athena WorkGroups developer docs](https://docs.aws.amazon.com/athena/latest/ug/workgroups.html)
6. Category tag (optional) -> Analytics

**Comment by jparkin** [comment]
This would be very helpful.  We are aiming to manage all of our resources in CFN.  Without workgroups we will be in a disjointed state.  Would appreciate the attention.

**Comment by PatMyron** [comment]
[`AWS::Athena::WorkGroup` documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-athena-workgroup.html)

[CloudFormation release history](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html)
