### ISSUE TITLE
AWS::CodePipeline::Pipeline-Tags

### ISSUE THREAD

**Issue by farski** [aws-cloudformation/aws-cloudformation-coverage-roadmap#95]
## 2. Scope of request 

Support resource tags on AWS::CodePipeline::Pipeline resources.

**Comment by luiseduardocolon** [comment]
We're looking at this, including ::Pipeline, ::Webhook, and ::CustomActionType as well.

**Comment by cfbarbero** [comment]
This was released on 10/31/19, right?
