### ISSUE TITLE
Ability to import permission sets into Cloudformation

### ISSUE THREAD

**Issue by DMEvanCT** [aws-cloudformation/aws-cloudformation-coverage-roadmap#963]
### Name of the resource

AWS::SSO::PermissionSet

### Resource name

AWS::SSO::PermissionSet

### Description

We want to be able to import existing AWS::SSO::PermissionSet into cloudformation so we can managed the permission sets through an automated process.

**Comment by AlJohri** [comment]
Can we re-open this? I don’t see it in the list of supported resources for CFN Import: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html

EDIT: Nevermind, appears to be a documentation issue. I was able to successfully import `AWS::SSO::PermissionSet` and `AWS::SSO::Assignment`.
